---
title: "cowichan_climate"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---

Climate Summaries for the CGOP for IPM project

```{r}
library(here)
library(tidyverse)
library(patchwork)
library(wesanderson)
theme_set(theme_classic(base_size = 18)) #for ggplot
```

```{r}
climate <- read.csv(here("clean_data", "CGOP_climatevalues.csv"))
climate <- climate %>% 
  mutate(year = as.character(year))
# scaling the climate variables
climate_scale <- climate %>% 
  select(1, c(ends_with("tot.precip"), ends_with(".temp")))
original_stats <- climate_scale %>%
  select(where(is.numeric)) %>%
  summarise(across(everything(),
      list(mean = ~mean(.x, na.rm = TRUE), sd   = ~sd(.x, na.rm = TRUE))))%>%
  pivot_longer(everything(),
                      names_to = c("variable", ".value"),
                      names_sep = "_")

j <- sapply(climate_scale, is.numeric)
climate_scale[j] <- scale(climate_scale[j])

climate_scale <- climate_scale %>%
    mutate_if(is.numeric, round, 3)
remove(j)


climate_long <- climate_scale %>%
  pivot_longer(cols = -year, names_to = "variable", values_to = "value") %>%
  mutate(season = str_extract(variable, "^[^.]+"),
    measurement = case_when(
      str_detect(variable, "precip") ~ "precip",
      str_detect(variable, "min\\.temp") ~ "min temp",
      str_detect(variable, "max\\.temp") ~ "max temp",
      str_detect(variable, "mean\\.temp") ~ "mean temp")) %>%
  select(year, season, measurement, value)%>%
  mutate(season = factor(season,
                         levels = c("spring", "summer", "fall", "winter")))

real <- climate %>%
  pivot_longer(cols = -year, names_to = "variable", values_to = "value") %>%
  mutate(season = str_extract(variable, "^[^.]+"),
    measurement = case_when(
      str_detect(variable, "precip") ~ "precip",
      str_detect(variable, "min\\.temp") ~ "min temp",
      str_detect(variable, "max\\.temp") ~ "max temp",
      str_detect(variable, "mean\\.temp") ~ "mean temp")) %>%
  select(year, season, measurement, value)%>%
  mutate(season = factor(season,
                         levels = c("spring", "summer", "fall", "winter")))
normals <- read.csv("C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/CowichanIPMs/clean_data/ClimateNA_normals.csv")
normals <- normals %>%
  dplyr::select(period, Tave_sp, Tmax_sp, Tmin_sp, PPT_sp, Tmax_wt, Tmin_wt, PPT_wt, Tave_wt, Tmax_at, Tmin_at, PPT_at, Tave_at, Tmax_sm, Tmin_sm, PPT_sm, Tave_sm)

future <- read.csv("C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/CowichanIPMs/clean_data/ClimateNA_SSPprojections.csv")
future <- future %>% 
  dplyr::select(period, Tave_sp, Tmax_sp, Tmin_sp, PPT_sp, Tmax_wt, Tmin_wt, PPT_wt, Tave_wt, Tmax_at, Tmin_at, PPT_at, Tave_at, Tmax_sm, Tmin_sm, PPT_sm, Tave_sm)

past <- read.csv("C:/Users/Jenna/OneDrive - The University Of British Columbia/Data Projects/CowichanIPMs/clean_data/ClimateNA_pastdata2000to2024.csv")
past <- past %>% 
  select(period, PPT_sp, Tmax_sm) %>% 
    mutate(year = str_extract(period, "\\d{4}")) %>%
  mutate(year = as.character(year))
  
```

```{r}
real <- real %>% 
  mutate(full_name = paste(season, measurement, sep = " "))
real_temp <- real %>% filter(grepl("temp", measurement))
real_precip <- real %>% filter(measurement == "precip")
normals_long <- normals %>%
  pivot_longer(cols = -period, names_to = "var", values_to = "normal_value") %>%
  mutate(
    season = case_when(
      var %in% c("PPT_sp","Tmin_sp","Tmax_sp","Tave_sp") ~ "spring",
      var %in% c("PPT_wt","Tmin_wt","Tmax_wt","Tave_wt") ~ "winter",
      var %in% c("PPT_sm","Tmin_sm","Tmax_sm","Tave_sm") ~ "summer",
      var %in% c("PPT_at","Tmin_at","Tmax_at","Tave_at") ~ "fall"),
    measurement = case_when(
      var %in% c("PPT_sp","PPT_wt","PPT_sm","PPT_at") ~ "precip",
      var %in% c("Tmin_sp","Tmin_wt","Tmin_sm","Tmin_at") ~ "min temp",
      var %in% c("Tmax_sp","Tmax_wt","Tmax_sm","Tmax_at") ~ "max temp",
      var %in% c("Tave_sp","Tave_wt","Tave_sm","Tave_at") ~ "mean temp"),
    period_label = period,
    full_name = paste(season, measurement, sep = " "))

normals_temp <- normals_long %>% filter(grepl("temp", measurement))
normals_precip <- normals_long %>% filter(measurement == "precip")


#Plot temperature histogram
(p_temp <- ggplot(real_temp, aes(x = value)) +
  geom_histogram(binwidth = .5, fill = "white", color = "black") +
    facet_wrap(~full_name, scales = "free", nrow = 4) +
    geom_vline(
    data = normals_temp,
    aes(xintercept = normal_value, color = period_label),
    linetype = "dashed", linewidth = 1) +
  theme_bw() +
  labs(
    x = "Temperature (°C)",
    y = "Count",
    title = "Histogram of CGOP Temperature Variables with Normals",
    color = "Normals Period") +
  scale_color_manual(values = c("dodgerblue", "#e8603d")))

#Plot precipitation histogram
(p_precip <- ggplot(real_precip, aes(x = value)) +
  geom_histogram(binwidth = 25, fill = "white", color = "black") +
  geom_vline(
    data = normals_precip,
    aes(xintercept = normal_value, color = period_label),
    linetype = "dashed", size = 1) +
  facet_wrap(~full_name, scales = "free") +
  theme_bw() +
  labs(
    x = "Precipitation (mm)",
    y = "Count",
    title = "Histogram of CGOP Precipitation with Normals",
    color = "Normals Period") +
  scale_color_manual(values = c("dodgerblue", "#e8603d")))

p_temp
p_precip
p_temp+p_precip

ggsave(plot = p_temp, here("Figures","climate","hist.temp.png"), width = 8, height = 6)
ggsave(plot = p_precip, here("Figures","climate","hist.precip.png"), width = 8, height = 6)


```

```{r}
#same but add in the future values
fut_long <- future %>%
  pivot_longer(cols = -period, names_to = "var", values_to = "future_value") %>%
  mutate(
    season = case_when(
      var %in% c("PPT_sp","Tmin_sp","Tmax_sp","Tave_sp") ~ "spring",
      var %in% c("PPT_wt","Tmin_wt","Tmax_wt","Tave_wt") ~ "winter",
      var %in% c("PPT_sm","Tmin_sm","Tmax_sm","Tave_sm") ~ "summer",
      var %in% c("PPT_at","Tmin_at","Tmax_at","Tave_at") ~ "fall"),
    measurement = case_when(
      var %in% c("PPT_sp","PPT_wt","PPT_sm","PPT_at") ~ "precip",
      var %in% c("Tmin_sp","Tmin_wt","Tmin_sm","Tmin_at") ~ "min temp",
      var %in% c("Tmax_sp","Tmax_wt","Tmax_sm","Tmax_at") ~ "max temp",
      var %in% c("Tave_sp","Tave_wt","Tave_sm","Tave_at") ~ "mean temp"),
    period_label = period,
    full_name = paste(season, measurement, sep = " "))

future_temp <- fut_long %>% filter(grepl("temp", measurement))
future_precip <- fut_long %>% filter(measurement == "precip")


#Plot temperature histogram
(p_temp <- ggplot(real_temp, aes(x = value)) +
  geom_histogram(binwidth = .5, fill = "white", color = "black") +
    facet_wrap(~full_name, scales = "free", nrow = 4) +
    geom_vline(
    data = subset(normals_temp, grepl("1971", period)),
    aes(xintercept = normal_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
        geom_vline(
    data = subset(future_temp, grepl("2011", period)),
    aes(xintercept = future_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
  theme_bw() +
  labs(
    x = "Temperature (°C)",
    y = "Count",
    title = "Histogram of CGOP Temperature Variables with Normals & short term SPP projections",
    color = "") +
  scale_color_manual(values = c(  "dodgerblue", "plum" ,"#fb8b24","#9a031e","#0f4c5c")))

#Plot precipitation histogram
(p_precip <- ggplot(real_precip, aes(x = value)) +
  geom_histogram(binwidth = 25, fill = "white", color = "black") +
    geom_vline(
    data = subset(normals_precip, grepl("1971", period)),
    aes(xintercept = normal_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
        geom_vline(
    data = subset(future_precip, grepl("2011", period)),
    aes(xintercept = future_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
  facet_wrap(~full_name, scales = "free") +
  theme_bw() +
  labs(
    x = "Precipitation (mm)",
    y = "Count",
    title = "Histogram of CGOP Precipitation with Normals & short term SPP projections",
    color = "") +
  scale_color_manual(values = c(  "dodgerblue", "plum" ,"#fb8b24","#9a031e","#0f4c5c")))

p_temp
p_precip
p_temp+p_precip

ggsave(plot = p_temp, here("Figures","climate","hist.spp.temp.png"), width = 10, height = 6)
ggsave(plot = p_precip, here("Figures","climate","hist.spp.precip.png"), width = 10, height = 6)


```

```{r}
#same but add in the future values


#Plot temperature histogram
(p_temp <- ggplot(real_temp, aes(x = value)) +
  geom_histogram(binwidth = .5, fill = "white", color = "black") +
    facet_wrap(~full_name, scales = "free", nrow = 4) +
    geom_vline(
    data = subset(normals_temp, grepl("1971", period)),
    aes(xintercept = normal_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
        geom_vline(
    data = subset(future_temp, grepl("2041", period)),
    aes(xintercept = future_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
  theme_bw() +
  labs(
    x = "Temperature (°C)",
    y = "Count",
    title = "Histogram of CGOP Temperature Variables with Normals & long term SPP projections",
    color = "") +
  scale_color_manual(values = c(  "dodgerblue", "plum" ,"#fb8b24","#9a031e","#0f4c5c")))

#Plot precipitation histogram
(p_precip <- ggplot(real_precip, aes(x = value)) +
  geom_histogram(binwidth = 25, fill = "white", color = "black") +
    geom_vline(
    data = subset(normals_precip, grepl("1971", period)),
    aes(xintercept = normal_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
        geom_vline(
    data = subset(future_precip, grepl("2041", period)),
    aes(xintercept = future_value, color = period_label),
    linetype = "dashed", linewidth = 1.2) +
  facet_wrap(~full_name, scales = "free") +
  theme_bw() +
  labs(
    x = "Precipitation (mm)",
    y = "Count",
    title = "Histogram of CGOP Precipitation with Normals & long term SPP projections",
    color = "") +
  scale_color_manual(values = c(  "dodgerblue", "plum" ,"#fb8b24","#9a031e","#0f4c5c")))

p_temp
p_precip
p_temp+p_precip

ggsave(plot = p_temp, here("Figures","climate","hist.spp.long.temp.png"), width = 10, height = 6)
ggsave(plot = p_precip, here("Figures","climate","hist.spp.long.precip.png"), width = 10, height = 6)


```
```{r}
(raw.norm <- ggplot(real, aes(x = year, y = value)) +
  geom_line(group = 1) +
  geom_hline(data = normals_long,
             aes(yintercept = normal_value, colour = period), linetype = "dashed") +
  facet_wrap(~full_name, scales = "free_y") +
  scale_colour_manual(values = c("dodgerblue", "#e8603d")) +
  theme_bw(base_size = 15) +
  labs(x = "", y = "Temp/Precip") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)))

ggsave(plot = raw.norm, here("Figures","climate", "raw.data.with.normals.png"), width = 13, height = 10)

#add in the mean for CGOP to that plot
real_means <- real %>%
  group_by(season, measurement) %>%
  summarise(mean_value = mean(value, na.rm = TRUE),
            .groups = "drop") %>% 
    mutate(full_name = paste(season, measurement, sep = " "))
  
(all.together <- ggplot(real, aes(x = year, y = value)) +
  geom_line(group = 1) +
  geom_hline(data = normals_long,
             aes(yintercept = normal_value,
                 colour = period), linetype = "dashed") +
   # Mean of real data
  geom_hline(data = real_means,
             aes(yintercept = mean_value),
             colour = "grey30",
             linewidth = 0.7) +
  facet_wrap(~full_name, scales = "free_y") +
  scale_colour_manual(values = c("dodgerblue", "#e8603d")) +
  theme_bw(base_size = 15) +
  labs(x = "", y = "Temp/Precip") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)))
ggsave(plot = all.together, here("Figures","climate", "raw.data.mean.with.normals.png"), width = 13, height = 10)


```

```{r samew thing but add in the spp data}
real_means <- real %>%
  group_by(season, measurement) %>%
  summarise(mean_value = mean(value, na.rm = TRUE),
            .groups = "drop") %>% 
    mutate(full_name = paste(season, measurement, sep = " "))

(raw.norm.spp.long <- ggplot(real, aes(x = year, y = value)) +
  geom_line(group = 1) +
  geom_hline(data = subset(normals_long, grepl("1971", period)),
             aes(yintercept = normal_value, colour = period), linetype = "dashed", linewidth = 1.2) +
  geom_hline(data = subset(fut_long, grepl("2041", period)),
             aes(yintercept = future_value, colour = period), linetype = "dashed", linewidth = 1.2) +
  geom_hline(data = real_means,
             aes(yintercept = mean_value),
             colour = "grey30",
             linewidth = 0.7) +
  facet_wrap(~full_name, scales = "free_y") +
  scale_color_manual(values = c(  "dodgerblue", "plum" ,"#fb8b24","#9a031e","#0f4c5c"))+
  theme_bw(base_size = 15) +
  labs(x = "", y = "Temp/Precip") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)))

ggsave(plot = raw.norm.spp.long, here("Figures","climate", "raw.data.with.normals.spp.png"), width = 15, height = 10)


#now shorter term
(raw.norm.spp.short <- ggplot(real, aes(x = year, y = value)) +
  geom_line(group = 1) +
  geom_hline(data = subset(normals_long, grepl("1971", period)),
             aes(yintercept = normal_value, colour = period), linetype = "dashed", linewidth = 1.2) +
  geom_hline(data = subset(fut_long, grepl("2040", period)),
             aes(yintercept = future_value, colour = period), linetype = "dashed", linewidth = 1.2) +
  geom_hline(data = real_means,
             aes(yintercept = mean_value),
             colour = "grey30",
             linewidth = 0.7) +
  facet_wrap(~full_name, scales = "free_y") +
  scale_color_manual(values = c(  "dodgerblue", "plum" ,"#fb8b24","#9a031e","#0f4c5c"))+
  theme_bw(base_size = 15) +
  labs(x = "", y = "Temp/Precip") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)))

ggsave(plot = raw.norm.spp.short, here("Figures","climate", "raw.data.with.normals.spp.long.png"), width = 15, height = 10)


```


```{r}
#Now, I wnat a figure that shows summer max temp and spring precip from weather station data, compared to climate NA past data
cgop_past <- real %>% 
  filter((season == "spring" & measurement == "precip") | (season == "summer" & measurement == "max temp")) 
past_long <- past %>%
  pivot_longer(cols = c(PPT_sp, Tmax_sm),
               names_to = "measurement",
               values_to = "value") %>%
  mutate(
    season = case_when(
      measurement == "PPT_sp" ~ "spring",
      measurement == "Tmax_sm" ~ "summer"),
    measurement = case_when(
      measurement == "PPT_sp" ~ "precip",
      measurement == "Tmax_sm" ~ "max temp"),
    source = "wna") %>%
  
  select(year, season, measurement, value, source)%>% 
    mutate(full_name = paste(season, measurement, sep = " "))

cgop_past <- cgop_past %>% mutate(source = "cgop")

combined <- bind_rows(past_long, cgop_past)

(comp <- ggplot(combined, aes(x = year, y = value, color = source, group = source)) +
  geom_line(linewidth = 1) +
  facet_wrap(~full_name, scales = "free_y") +
  theme_bw(base_size = 15) +
   geom_hline(
    data = normals_long %>% 
      filter((season == "spring" & measurement == "precip") |
             (season == "summer" & measurement == "max temp")),
    aes(yintercept = normal_value, colour = period), linetype = "dashed") +
  labs(x = "Year", y = "Precip/Temp", color = "Dataset") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.background = element_rect(fill = "white"),
    strip.text = element_text(face = "bold"))+
    scale_color_manual(values = c("black", "dodgerblue", "#e8603d", "grey50")))
ggsave(plot = comp,here("Figures","climate", "cgop.wna.comparison.png"), width = 15, height = 7)

```

```{r}
(scal <- climate_long %>% 
  ggplot(aes(x = year, y = value, group = interaction(season, measurement), color = measurement))+
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey80") +
  geom_line()+  
  theme_bw(base_size = 18) +
  facet_wrap(~season)+
   theme(axis.text.x = element_text(angle = 45, hjust = 1),
             strip.background = element_rect(fill = "white"))+
  scale_color_manual(values = c("red", "grey40", "deepskyblue", "blue4"))+
  labs(x = "", y = "Scaled climate", color = ""))

ggsave(plot = scal,here("Figures","climate", "scaled.line_cgop.data.mean.png"), width = 10, height = 7)
```

```{r historical climate}
# read in data from ClimateNA (long term averages)
longterm <- read.csv("C:/Users/Jenna/Dropbox/Williams' Lab/Cowichan IDE/LoggerData/ClimateNA/ClimateNA_CGOP_ClimateData.csv")
#the variables I want here are:
## Tave_sp	spring mean temperature (°C)
##  	Tmax_sp	spring mean maximum temperature (°C)
## Tmin_sp	spring mean minimum temperature (°C)
##  	PPT_sp	spring precipitation (mm)
## MAP	mean annual precipitation (mm)
## they define spring as MArch, April, and May
longterm <- longterm %>% 
  dplyr::select(period, Tave_sp, Tmax_sp, Tmin_sp, PPT_sp, MAP, Tave_sm, Tmax_sm, Tmin_sm, PPT_sm,Tave_wt, Tmax_wt, Tmin_wt, PPT_wt, Tave_at, Tmax_at, Tmin_at, PPT_at)

PPT_sp <- longterm$PPT_sp[[1]]

(precip <- real %>% filter(measurement == "precip") %>% 
    ggplot(aes(x = year, y = value))+
  geom_col(fill = wes_palettes$Darjeeling2[2], color = "black")+
  labs(y = "Total precipitation (mm)", x = "Year")+
  #geom_hline(yintercept = PPT_sp, linetype='dashed')+
  #annotate("text", x = "2024", y = PPT_sp, label = "1961-1990 Spring Precip", vjust = -0.5)+
  #scale_y_continuous(expand = c(0,0), n.breaks = 15)+
  theme_bw(base_size = 18) +
  facet_wrap(~season)+
   theme(axis.text.x = element_text(angle = 45, hjust = 1),
             strip.background = element_rect(fill = "white")))

(temp <- real %>% filter(measurement != "precip") %>% 
  ggplot(aes(x = year, y = value, group = measurement, color = measurement)) + 
  geom_line()+
  labs(y = "Temperature (C)", x = "Year", color = "")+
  theme(legend.position="none")+
  scale_color_manual(values = c("red", "grey40", "deepskyblue")) +
  theme_bw(base_size = 18) +
  facet_wrap(~season)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
             strip.background = element_rect(fill = "white")))

(raw_climate <- temp+precip+ plot_layout(guides = "collect") & theme(legend.position = 'bottom'))

ggsave(plot = raw_climate, here("figures", "climate", "raw values.png"), width = 15, height = 8)
#really winter should be first here!

```

```{r histograms}

(hist <- ggplot(climate_long, aes(x = value, fill = measurement)) +
  geom_histogram(binwidth = 1, color = "black")+
  facet_grid(season ~ measurement) +
  theme_bw(base_size = 18) +
    scale_fill_manual(values = c("red", "grey40", "deepskyblue", wes_palettes$Darjeeling2[2]))+
  labs(x = "standardized climate", fill = "")+
   theme(strip.background = element_rect(fill = "white")))
ggsave(plot = hist, here("Figures", "climate", "histogram.png"), width = 8, height = 8)

```

```{r}
cor.data <- climate_scale %>%
  select(where(is.numeric)) %>% 
  drop_na()
cor_mat <- climate_scale %>%
  select(where(is.numeric)) %>%
  cor(use = "pairwise.complete.obs")

cor_mat
cor_mat %>%
  as.data.frame() %>%
  tibble::rownames_to_column("var1") %>%
  pivot_longer(-var1, names_to = "var2", values_to = "cor") %>%
  filter(var1 != var2, abs(cor) > 0.7) %>%
  arrange(desc(abs(cor)))
corrplot::corrplot(cor_mat, method = "color")

#MAKE CORRELATION MATRI
library(corrplot)

M<-cor(cor.data[,-1])
res1 <- cor.mtest(cor.data[,-1], conf.level = 0.95)
ord <- corrMatOrder(M, order = "AOE")

png(here("Figures", "climate", "corrplot.png"), width = 1500, height = 1500, res = 150)
corrplot(M, p.mat = res1$p, method="circle",type="upper",insig = "p-value", sig.level=-1) #to show all p values set sig.level = -1, to show insig ones set to 0.05
dev.off()
#where p<0./05 there is a significant linear correlation

png(here("Figures", "climate", "corrscatter.png"), width = 1500, height = 1500, res = 150)
pairs(climate_scale[,-1], upper.panel = NULL, pch = 20, cex = 1.5)
dev.off()

#variables that are correlated: 
#- min, mean, and max winter temp --> use winter mean
# summer mean and max temp
# summer mean and min temp --> use summer max and min (not correlated)
# spring mean, min, and max temp--> use spring mean temp

#fall min and mean temp --> fall mean and max temp
#summer max temp and summer precip --> p=0.05



```

Simulation to see how much z-scores change with increasing years of data
```{r}
z <- real %>%
  group_by(full_name) %>%
  mutate(
    z_value = (value - mean(value, na.rm = TRUE)) / 
              sd(value, na.rm = TRUE)
  ) %>%
  ungroup()

z %>%
  group_by(full_name) %>%
  summarise(mean_z = mean(z_value),
            sd_z   = sd(z_value))

##

real <- real %>%
  mutate(year = as.numeric(year))

start_year <- 2013
end_year   <- max(real$year)

z_expanding <- map_dfr((start_year + 2):end_year, function(y_end) {
  
  real %>%
    filter(year >= start_year, year <= y_end) %>%
    group_by(full_name) %>%
    mutate(
      z_value = (value - mean(value, na.rm = TRUE)) /
                sd(value, na.rm = TRUE),
      window_end = y_end,
      n_years    = window_end - start_year + 1   # <-- number of years in baseline
    ) %>%
    ungroup()
})

#just 2015 spring value
z_expanding %>%
  filter(year == 2015, full_name == "spring precip") %>%
  ggplot(aes(x = n_years, y = z_value)) +
  geom_line(group = 1, color = "black") +
  geom_point(color = "black") +
  labs(
    title = "Z-score of 2015 Spring Precipitation",
    x = "Number of years included since 2013",
    y = "Z-score"
  )
z_expanding %>%
  filter(full_name == "spring precip") %>%  # all years
  ggplot(aes(x = n_years, y = z_value, color = factor(year))) +
  geom_line() +
  geom_point() +
  labs(
    title = "Z-scores of Spring Precipitation",
    x = "Number of years included for mean and st dev (since 2013)",
    y = "Z-score",
    color = "Year Measurement"
  )

z_expanding %>%
  ggplot(aes(x = n_years, y = z_value, color = factor(year))) +
  geom_line() +
  geom_point() +
  facet_wrap(~full_name, scales = "free_y") +  
  scale_x_continuous(breaks = seq(2, 13, by = 2)) +
  labs(
    x = "Number of years included for mean and SD (since 2013)",
    y = "Z-score",
    color = "Year"
  ) +
  theme_minimal()

z_expanding_filtered <- z_expanding %>%
  filter(full_name == "spring precip" |full_name == "summer max temp")

# Plot
(sim.z <- ggplot(z_expanding_filtered, aes(x = n_years, y = z_value, color = factor(year))) +
  geom_line() +
  geom_point() +
  facet_wrap(~full_name, scales = "free_y") +
  scale_x_continuous(breaks = seq(min(z_expanding_filtered$n_years),
                                  max(z_expanding_filtered$n_years), by = 1)) +
  labs(title = "CGOP",
    x = "Length of dataset",
    y = "Z-score",
    color = "Observation Year") +
  theme_bw()+
  theme(
    strip.background = element_rect(fill = "white", color = "black"),
    strip.text = element_text(color = "black"))
)
ggsave(plot = sim.z, here("Figures", "climate", "simulated.zscore.png"), width = 8, height = 4)

```

Do the same for the climate NA long term data (since 2000)
```{r}
past <- past %>%
  mutate(year = as.numeric(year))
past_long <- past %>%
  pivot_longer(
    cols = c(PPT_sp, Tmax_sm),
    names_to = "variable",
    values_to = "value"
  )%>%
  mutate(
    variable = case_when(
      variable == "PPT_sp" ~ "Spring Precipitation",
      variable == "Tmax_sm" ~ "Summer Max Temp",
      TRUE ~ variable
    )
  )
start_year <- 2000
end_year   <- max(past_long$year)

past_z_expanding <- map_dfr((start_year + 2):end_year, function(y_end) {
  
  past_long %>%
    filter(year >= start_year, year <= y_end) %>%
    group_by(variable) %>%
    mutate(
      z_value   = (value - mean(value, na.rm = TRUE)) / sd(value, na.rm = TRUE),
      window_end = y_end,
      n_years   = window_end - start_year + 1
    ) %>%
    ungroup()
})
(wna.zscores <- past_z_expanding %>%
  ggplot(aes(x = n_years, y = z_value, color = factor(year))) +
  geom_line() +
  geom_point() +
  facet_wrap(~variable, scales = "free_y") +
  labs(
    title = "ClimateWNA past data",
    x = "Length of dataset",
    y = "Z-score",
    color = "Observation Year") +
    theme_bw()+
     theme(
    strip.background = element_rect(fill = "white", color = "black"),
    strip.text = element_text(color = "black"))
  )
ggsave(plot = wna.zscores, here("Figures", "climate", "simulated.wna.zscore.png"), width = 8, height = 4)

```

