---
title: "dactylis.ipm"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---

```{r packages}
## Primula vital rates with climate data

library(tidyverse)
library(AICcmodavg)
library(lme4)
library(patchwork) #for putting plots into one
library(popbio)
theme_set(theme_classic(base_size = 18)) #for ggplot
```

```{r}
dac <- read.csv(here("clean_data", "Dactylis_Demography_Data_CLEANED_2016thru2025.csv"))
climate <- read.csv(here("clean_data", "CGOP_climatevalues_scaled.csv"))
climate<- climate %>%
  arrange(year) %>%
  mutate(across(-year, ~lag(.x), .names = "prev_{.col}"))

dac <- left_join(dac, climate, by = c("Year" = "year"))
dac <- dac %>% 
  mutate(Year = as.factor(Year), 
         Plot = as.factor(Plot),
         survT = as.factor(survT),
         survT1 = as.factor(survT1),
         pflowerT = as.factor(pflowerT),
         pflowerT1 = as.factor(pflowerT1),
         log.no.stems = log(No.stems),
         log.no.stemsT1 = log(No.stemsT1),
        trt = as.factor(trt),
        trt = fct_relevel(trt, "irrigated", "control", "drought"))

dac <- dac %>% 
  filter(!(Plot %in% c("4", "5", "15")))

gm.summer.p <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
fm.base.size <- glmer(pflowerT ~ log.no.stems + (1|Plot) + (1|Year), data = dac, family = "binomial")
sm.summer.av.temp.int <- glmer(survT1 ~ log.no.stems*summer.mean.max.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
poisson.gs.av.temp.trt.int2 <- glmer(No.panicles ~ log.no.stems + spring.mean.temp*trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")

dac.new <- dac %>% 
  filter(stage == "seedling")
#parameters for new plants
new_sd <- sd(dac.new$log.no.stems)
new_mean <- mean(dac.new$log.no.stems, na.rm = T)
hist(dac.new$log.no.stems)

#Define the min and max size, which are the integration bounds of the IPM.
minRealsize <- min(dac$log.no.stems, na.rm=T) 
maxRealsize <- 1.1* max(dac$log.no.stems,na.rm=T)

#now add a new min & max size to keep the plants in for eviction
##note: this could be wrong for dactylis because -1 no stems seem weird! come back to this
min.size <-minRealsize-1 #lower
max.size <-maxRealsize+1.5 #upper
```

```{r}
#pancile to seedlings proxy:
#panciles in year t is a function of the number of panicles in the plot in the year prior
#so to get the transition rate: number of seedlings in t/#panciles year t-1 (PER PLOT - for now)
plot_summary <- dac %>%
  group_by(Plot, Year) %>%
  summarise(
    seedlings_t = sum(stage == "seedling", na.rm = TRUE),
    panicles_t = sum(No.panicles, na.rm = TRUE),
    .groups = "drop") %>% 
  drop_na()
plot_summary <- plot_summary %>% 
  arrange(Plot, Year) %>%
  group_by(Plot) %>%
  mutate(panicles_tminus1 = lag(panicles_t)) %>%
  drop_na() %>% 
 # ungroup() %>% 
  mutate(germ.rate = seedlings_t/panicles_tminus1) %>% 
  filter(is.finite(germ.rate))
pest <- mean(plot_summary$germ.rate)
#this is coarse! But ok for the first stab
```

```{r parameters , echo=FALSE}
#this is for range of climates
rows <- expand.grid(summer.mean.max.temp = seq(-2, 2, by = 0.5), spring.mean.temp = seq(-2, 2, by = 0.5), trt = c("control", "drought", "irrigated"), summer.tot.precip = seq(-2, 2, by = 0.5)) 
#set up an empty parameter df
params=data.frame(
	growth.int = c(NA),
	growth.slope  = NA,
	growth.sd=NA,
	surv.int=NA,
	surv.slope=NA,
	pflow.int = NA,
	pflow.slope = NA,
	no.flow.int=NA,
	no.flow.slope=NA,
	recruit.size.mean=NA,
	recruit.size.sd=NA,
	pest = NA
)
params <- bind_cols(params, rows)
```

```{r}
#gm.summer.p <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
#growth intercept
for (i in 1:nrow(params)) {
    params$growth.int[i] <- fixef(gm.summer.p)[1] + fixef(gm.summer.p)[3] * params$summer.mean.max.temp[i]
}

#growth slope
params$growth.slope <- fixef(gm.summer.p)[2]

growth_var <- as.data.frame(VarCorr(gm.summer.p)) #assumes same variance across all
params$growth.sd <- growth_var[growth_var$grp=="Residual","sdcor"] # growth sd of residuals

### pflower
#fm.base.size <- glmer(pflowerT ~ log.no.stems + (1|Plot) + (1|Year), data = dac, family = "binomial")

#intercept
params$pflow.int <- fixef(fm.base.size)[1]

#slope:
params$pflow.slope <- fixef(fm.base.size)[2]

### no.flowers
#poisson.gs.av.temp.trt.int2 <- glmer(No.panicles ~ log.no.stems + spring.mean.temp*trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")
#intercept
for (i in 1:nrow(params)) {
  if (params$trt[i] == "control") {
    params$no.flow.int[i] <- fixef(poisson.gs.av.temp.trt.int2)[1] + fixef(poisson.gs.av.temp.trt.int2)[3] * params$spring.mean.temp[i] + fixef(poisson.gs.av.temp.trt.int2)[4] + fixef(poisson.gs.av.temp.trt.int2)[6] * params$spring.mean.temp[i] 
  } else if (params$trt[i] == "irrigated") {
    params$no.flow.int[i] <- fixef(poisson.gs.av.temp.trt.int2)[1] + fixef(poisson.gs.av.temp.trt.int2)[3] * params$spring.mean.temp[i]
  } else if (params$trt[i] == "drought") {
    params$no.flow.int[i] <- fixef(poisson.gs.av.temp.trt.int2)[1] + fixef(poisson.gs.av.temp.trt.int2)[3] * params$spring.mean.temp[i] + fixef(poisson.gs.av.temp.trt.int2)[5]+ fixef(poisson.gs.av.temp.trt.int2)[7] * params$spring.mean.temp[i] 
  }
}
#slope
params$no.flow.slope <- fixef(poisson.gs.av.temp.trt.int2)[2]


##survival:
#sm.summer.av.temp.int <- glmer(survT1 ~ log.no.stems*summer.mean.max.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
#slope
for (i in 1:nrow(params)) {
  params$surv.slope[i] <- fixef(sm.summer.av.temp.int)[2] + fixef(sm.summer.av.temp.int)[4] * params$summer.mean.max.temp[i]
  params$surv.int[i] <- fixef(sm.summer.av.temp.int)[1] + fixef(sm.summer.av.temp.int)[3] * params$summer.mean.max.temp[i]
}

#params$no.seeds <- no.seeds
params$pest <- pest
params$recruit.size.mean <- new_mean # mean new >1 leaf plant size
params$recruit.size.sd<- new_sd # sd of new >1 leaf plant size
```

```{r}
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
###         Load functions
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#SURVIVAL AT SIZE X
s.x=function(x,params) {
	u=exp(params$surv.int+params$surv.slope*x)
	return(u/(1+u))
}

#how to test this: 
### run function for a plant of size 1 and for the first row of parameters
#s.x(x = 1, params = params[1,])
### run function for a plant of size 1 but for all rows of parameters (so get a list )
#s.x(x = 1, params = params)
#ok this works and seems to work for all rows of params. great.

#GROWTH FROM SIZE X TO Y; 
  ## returns a *probability density distribution* for each x value
g.yx<-function(y,x,params){
    # eviction here...
  xb=pmin(pmax(x,minRealsize),maxRealsize) #Transforms all values below/above limits in min/max size (floor & ceiling)
  growth_to_newsize <-params$growth.int + params$growth.slope*xb
  growth_sd <- params$growth.sd
  return(dnorm(y,mean=growth_to_newsize,sd=growth_sd))
  #dnorm(y,mean=params$growth.int + params$growth.slope*x,sd=params$growth.sd)
}

#Tom Miller's combined s and g kernel
P <- function(y, x, params){
  s.x(x, params)*g.yx(y, x, params)
}

#PROBABILITY OF FLOWERING OF SIZE X individuals
pf.x <-function(x,params){
	u<-exp(params$pflow.int+params$pflow.slope*x)
	return(u/(1+u))
}
#testing this for a plant of size 5
#pf.x(x = 8,params = params_expanded)

f.yx <- function(x,params) { 		
  return(pf.x(x,params)*exp(params$no.flow.int+params$no.flow.slope*x)* params$pest)
}
##so this should be outputting the number of seedlings made? Yes
#f.yx(x = 7,params = params_original)


##do big plants make a million flowers?
#exp(params$no.flow.int+params$no.flow.slope*8) 
## no they make a reasonable amount

#SIZE DISTRIBUTION OF RECRUITS - so the ones going from the continuous into the continuous stage. 
recruit.size<-function(y,params){
    ## returns a *probability density distribution*
  dnorm(y,mean=params$recruit.size.mean,sd=params$recruit.size.sd)
}
```

```{r}
params_list <-  filter(params) %>% split(., seq(nrow(.))) #this splits up params into X rows, which I can feed into the function below

###
mat.size = 100 #dimensions of continuous matrix
bigmatrix <- function(params_list, mat.size){

  n <- mat.size
  L <- min.size
  U <- max.size

  # mesh
  h <- (U - L) / n
  b <- L + c(0:n) * h
  y <- 0.5 * (b[1:n] + b[2:(n+1)])

  # Fertility matrix
  Fmat <- matrix(0, n, n)

  # recruits of size y from parent size x
  Fmat <- outer(y, y, function(y,x){
    f.yx(x, params_list) * recruit.size(y, params_list)
  }) * h

  # Growth/survival
  Tmat <- t(outer(y, y, P, params = params_list)) * h

  # Full kernel
  IPMmat <- Fmat + Tmat

  out_matrix <- list(
    IPMmat = IPMmat,
    Fmat = Fmat,
    Tmat = Tmat,
    meshpts = y)

  out_lamb <- data.frame(
    lambda = lambda(IPMmat),
    summer.mean.max.temp = params_list$summer.mean.max.temp,
    spring.temp = params_list$spring.mean.temp,
    summer.tot.precip = params_list$summer.tot.precip,
    trt = params_list$trt)

  return(out_lamb)
}

#what I want returned is lambdas
lamb_lists <- lapply(X = params_list, FUN = bigmatrix, mat.size = mat.size) #for each row of params_list, run the big matrix function!

#great~! now make it a df
dac_lambda <- do.call(rbind, lamb_lists)

```

```{r}
ggplot(dac_lambda, aes(x = summer.mean.max.temp, y = spring.temp, fill = lambda)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 1.45) +
  labs(x = "Summer Temperature", y = "Spring Temperature", fill = expression(lambda)) +
  facet_wrap(~ trt) +
  theme_minimal(base_size = 14)
ggplot(dac_lambda, aes(x = summer.mean.max.temp, y = spring.temp, fill = lambda)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 1.4) +
  labs(x = "Summer Temperature", y = "Spring Temperature", fill = expression(lambda)) +
  facet_grid(summer.tot.precip ~ trt) +
  theme_minimal(base_size = 14)
```


```{r}
y_limits <- c(1.05, 1.75)
(summer.temp <- dac_lambda %>%
  filter(spring.temp == 0, summer.tot.precip == 0) %>% 
  ggplot(aes(x = summer.mean.max.temp, y = lambda, color = trt)) +
  geom_line(size = 1.2) +
  geom_point(size = 2) +
  scale_y_continuous(limits = y_limits) +
  scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3"))+
  labs(
    x = "Summer Temperature",
    y = expression(lambda),
    color = ""
  ) )
(precip <- dac_lambda %>%
  filter(spring.temp == 0, summer.mean.max.temp == 0) %>% 
  ggplot(aes(x = summer.tot.precip, y = lambda, color = trt)) +
  geom_line(size = 1.2) +
  scale_y_continuous(limits = y_limits) +
  geom_point(size = 2) +
  scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3"))+
  labs(
    x = "Summer Precipitation",
    y = expression(lambda),
    color = ""
  ) )
(sp.temp <- dac_lambda %>%
  filter(summer.tot.precip == 0, summer.mean.max.temp == 0) %>% 
  ggplot(aes(x = spring.temp, y = lambda, color = trt)) +
  geom_line(size = 1.2) +
  scale_y_continuous(limits = y_limits) +
  scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3"))+
  geom_point(size = 2) +
  labs(
    x = "Spring Temperature",
    y = expression(lambda),
    color = ""
  ) )
(together <- summer.temp+precip+sp.temp+ plot_layout(guides = "collect", axis_titles = "collect") &
  theme(legend.position = "bottom"))

ggsave(here("Figures", "Dactylis", "dactylis.pop.growth.png"), plot = together, width = 10, height =5)

```


