---
title: "dactylis"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
library(here)
library(tidyverse)
library(lme4)
library(AICcmodavg)
library(patchwork)
library(gt) #for saving tables in a word doc

theme_set(theme_classic(base_size = 18)) #for ggplot

```

```{r}
dac <- read.csv(here("clean_data", "Dactylis_Demography_Data_CLEANED_2016thru2026.csv"))
climate <- read.csv(here("clean_data", "CGOP_climatevalues_scaled.csv"))
climate<- climate %>%
  arrange(year) %>%
  mutate(across(-year, ~lag(.x), .names = "prev_{.col}"))

dac <- left_join(dac, climate, by = c("Year" = "year"))
dac <- dac %>% 
  mutate(Year = as.factor(Year), 
         Plot = as.factor(Plot),
         survT = as.factor(survT),
         survT1 = as.factor(survT1),
         pflowerT = as.factor(pflowerT),
         pflowerT1 = as.factor(pflowerT1),
         log.no.stems = log(No.stems),
         log.no.stemsT1 = log(No.stemsT1),
        trt = as.factor(trt),
        trt = fct_relevel(trt, "irrigated", "control", "drought"))

dac <- dac %>% 
  filter(!(Plot %in% c("4", "5", "15")))

dac.surv <- dac %>% 
  filter(!Year =="2026",
  !is.na(survT1)) 
```

```{r ground truthing lambda}
lam <- dac %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  group_by(Year, Plot) %>%
  summarise(
    n = sum(survT == 1, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Plot, Year) %>%
  group_by(Plot) %>%
  mutate(
    lambda.plot = lead(n) / n,
    lambda.plot = na_if(lambda.plot, NaN)
  ) %>%
  ungroup()

lam.all <- dac %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  group_by(Year) %>%
  summarise(
    n = sum(survT == 1, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Year) %>%
  mutate(
    lambda = lead(n) / n
  )
  
(lambda <- ggplot(lam, aes(x = as.character(Year), y = lambda.plot, color = Plot)) +
  geom_line(aes(group = Plot), alpha = 0.5) +
  geom_point() +
  geom_hline(yintercept = 1)+
  labs(x = "Year", y = expression(lambda)) +
  theme_minimal())
(n <- ggplot(lam, aes(x = as.character(Year), y = n, color = Plot)) +
  geom_line(aes(group = Plot), alpha = 0.5) +
  geom_point() +
  labs(x = "Year", y = "Number of plants") +
  theme_minimal())
(n.size <- 
  lam.all %>%
  group_by(Year) %>%
  summarise(n = sum(n, na.rm = TRUE), .groups = "drop") %>%
  ggplot(aes(x = Year, y = n, group = 1)) +
  geom_line(alpha = 0.5) +
  geom_point() +
  labs(x = "Year", y = "Number of plants") +
  theme_minimal())

(lambda.size <- ggplot(lam.all, aes(x = as.character(Year), y = lambda, group = 1)) +
  geom_line(alpha = 0.5) +
  geom_point() +
  geom_hline(yintercept = 1)+
  labs(x = "Year", y = expression(lambda)) +
  theme_minimal())

(to.plot <- lambda/n +plot_layout(guides = "collect")
)
ggsave(here("Figures", "Dactylis", "groundtruth.lambda.perplot.png"), plot = to.plot, width = 8, height =6)

(to <- lambda.size/n.size +plot_layout(guides = "collect")
)

ggsave(here("Figures", "Dactylis", "groundtruth.lambda.png"), plot = to, width = 8, height =6)

```


```{r what size metric to use, and for pflower}
#whats a better size measurement - log(no.stems *height) or log(no.stems)?
dac_size_complete <- dac %>%
  arrange(Plot, Year) %>%
  group_by(Plot) %>%
  mutate(
    log_stem_height = log(No.stems * Height),
    log_stem_height_lag = lag(log_stem_height)
  ) %>%
  ungroup() |> 
  filter(
    complete.cases(
      log_stem_height,
      log_stem_height_lag,
      log.no.stems,
      log.no.stemsT1,
      Plot
    )
  )
#dac_size_complete <- dac[complete.cases(dac[, c("log_stem_height", "log_stem_height_lag", "log.no.stems", "log.no.stemsT1", "Plot")]), ]

size.test1 <- lmer(log.no.stemsT1 ~ log.no.stems + (1|Plot) + (1|Year), data = dac_size_complete, REML = F)

size.test2 <- lmer(log_stem_height_lag ~ log_stem_height + (1|Plot) + (1|Year), data = dac_size_complete, REML = F)
AIC(size.test1, size.test2)
#first one

#size in current year or past year for flowering
dac_complete <- dac[complete.cases(dac[, c("pflowerT", "pflowerT1", "log.no.stems", "Year", "Plot")]), ]
f.test1  <- glmer(pflowerT ~ log.no.stems+ (1|Year) + (1|Plot) , data = dac_complete, family = "binomial")
f.test2  <- glmer(pflowerT1 ~ log.no.stems+ (1|Year) + (1|Plot) , data = dac_complete, family = "binomial")
AIC(f.test1, f.test2) #one is better

table(dac$survT1, dac$Year)
table(dac$pflowerT, dac$Year)
table(dac$stage, dac$Year)
table(dac$No.panicles, dac$Year)

summary_df <- dac %>%
  group_by(Plot, Year) %>%
  summarise(
    panciles_t = sum(No.panicles, na.rm = TRUE),
    seedlings_t = sum(stage=="seedling", na.rm = TRUE),
    .groups = "drop"
  )
summary_df
t_t1_table <- summary_df %>%
  mutate(seedlings_t1 = lead(seedlings_t)) %>% 
  mutate(seedlings_per_panicle = ifelse(
    panciles_t == 0 | is.na(panciles_t) | is.na(seedlings_t1),
    NA,
    seedlings_t1 / panciles_t
  ))
mean_seedlings_per_panicle <- mean(
  t_t1_table$seedlings_per_panicle,
  na.rm = TRUE
)
sd_seedlings_per_panicle <- sd(
  t_t1_table$seedlings_per_panicle,
  na.rm = TRUE
)
median_seedlings_per_panicle <- median(
  t_t1_table$seedlings_per_panicle,
  na.rm = TRUE
)
#0.096
#0.095 after 2026
```

```{r growth prequel}
base <- lmer(log.no.stemsT1 ~ log.no.stems*Year + (1|Plot), data = dac, REML = F)
drop1(base,test="Chisq")
base2 <- lmer(log.no.stemsT1 ~ log.no.stems+Year + (1|Plot), data = dac, REML = F)
base3 <- lmer(log.no.stemsT1 ~ log.no.stems+ (1|Plot), data = dac, REML = F)
a2 <- anova(base3, base2, test="LRT") #yes year is significant
best.growth <- lmer(log.no.stemsT1 ~ log.no.stems + (1|Year) + (1|Plot), data = dac, REML = F)

re_year <- rownames_to_column(
  as.data.frame(ranef(best.growth)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year))

# 
grow.corr <- left_join(re_year, climate) %>% 
  select(-year)
names(grow.corr)[names(grow.corr) == "(Intercept)"] <- "int"
cor_matrix <- cor(grow.corr)
correlations <- cor_matrix[,"int"]

correlations <- correlations[names(correlations) != "int"]
correlations_sorted <- sort(correlations, decreasing = TRUE)
###
vars <- names(grow.corr)[names(grow.corr) != "int"]

# Compute correlations and p-values
cor_results <- lapply(vars, function(v) {
  test <- cor.test(grow.corr$int, grow.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_growth <- do.call(rbind, cor_results)

#summer tot.precip only with with correlation

#summer.tot.precip
#spring.mean.min.temp
###
#these are the ones to test
# vars <- c("summer.tot.precip", "spring.mean.min.temp",
#           "prev_summer.tot.precip", 
#           "summer.mean.max.temp")
# 
# # Unique climate-year values
dac.unique <- dac %>%
  distinct(Year, across(all_of(vars)))
cor.test(dac.unique$summer.tot.precip, dac.unique$spring.mean.min.temp)
# 
# # All pairwise combinations
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# cor_results <- map_dfr(pairs, function(p) {
#   x <- dac.unique[[p[1]]]
#   y <- dac.unique[[p[2]]]
#   ct <- cor.test(x, y)
#   tibble(
#     var1 = p[1],
#     var2 = p[2],
#     estimate = unname(ct$estimate),
#     statistic = unname(ct$statistic),
#     p.value = ct$p.value,
#     conf.low = ct$conf.int[1],
#     conf.high = ct$conf.int[2]
#   )
# })
# 
# cor_results
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# pairs
#dont test  "summer.tot.precip"    "summer.mean.max.temp"...correlated
```

```{r growth model selection}
gm.base.size <- lmer(log.no.stemsT1 ~ log.no.stems + (1|Plot) + (1|Year), data = dac, REML = F)
gm.base.trt <- lmer(log.no.stemsT1 ~ log.no.stems+ trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.base.trt.int <- lmer(log.no.stemsT1 ~ log.no.stems*trt + (1|Plot) + (1|Year), data = dac, REML = F)

#spring.mean.min.temp
gm.sp.min.temp <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + (1|Plot) + (1|Year), data = dac, REML = F)
gm.sp.min.temp.trt <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.sp.min.temp.trt.int2 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp*trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.gs.av.temp.int <- lmer(log.no.stemsT1 ~ log.no.stems*trt +spring.mean.min.temp + (1|Plot) + (1|Year), data = dac, REML = F)
gm.gs.av.temp.int2 <- lmer(log.no.stemsT1 ~ log.no.stems*trt +spring.mean.min.temp*trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.sp.min.temp.q <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + I(spring.mean.min.temp^2) + (1|Plot) + (1|Year), data = dac, REML = F)

#summer.tot.precip
gm.summer.p <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
gm.summer.p.trt <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.summer.p.trt.int <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip*trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.summer.p.trt.int2 <- lmer(log.no.stemsT1 ~ log.no.stems*trt+summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
gm.summer.p.trt.int3 <- lmer(log.no.stemsT1 ~ log.no.stems*trt+summer.tot.precip*trt + (1|Plot) + (1|Year), data = dac, REML = F)
gm.summer.q <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + I(summer.tot.precip^2)+ (1|Plot) + (1|Year), data = dac, REML = F)

# 
# #prev_summer.tot.precip
# gm.psummer.p <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.psummer.p.trt <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip + trt + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.psummer.p.trt.int <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip*trt + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.psummer.p.trt.int2 <- lmer(log.no.stemsT1 ~ log.no.stems*trt+prev_summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.psummer.q <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip + I(prev_summer.tot.precip^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
# 
# #summer.mean.max.temp
# gm.summer.t <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.summer.t.trt <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + trt + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.summer.t.trt.int <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp*trt + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.summer.t.trt.int2 <- lmer(log.no.stemsT1 ~ log.no.stems*trt+summer.mean.max.temp + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.summer.t.q <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + I(summer.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac, REML = F)
# 
# #"spring.mean.min.temp" "summer.mean.max.temp"
# gm.su.sp.t <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + summer.mean.max.temp + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.t1 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + summer.mean.max.temp + I(spring.mean.min.temp^2) +(1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.t2 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + summer.mean.max.temp + I(summer.mean.max.temp^2) +(1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.trt.t <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + trt + summer.mean.max.temp+(1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.trt.int.t <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp*trt +summer.mean.max.temp+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.trt.int2.t <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp*trt +spring.mean.min.temp+ (1|Plot) + (1|Year), data = dac, REML = F)
# 
# #"summer.tot.precip"    "spring.mean.min.temp"
gm.su.sp <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp1 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + summer.tot.precip + I(summer.tot.precip^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp2 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + summer.tot.precip + I(spring.mean.min.temp^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp.trt <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + trt + summer.tot.precip+(1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp.trt.int <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp*trt +summer.tot.precip+ (1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp.trt.int2 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip*trt +spring.mean.min.temp+ (1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp.trt.int3 <- lmer(log.no.stemsT1 ~ log.no.stems*trt + summer.tot.precip*trt +spring.mean.min.temp+ (1|Plot) + (1|Year), data = dac, REML = F)
gm.su.sp.trt.int4 <- lmer(log.no.stemsT1 ~ log.no.stems*trt + summer.tot.precip +spring.mean.min.temp*trt+ (1|Plot) + (1|Year), data = dac, REML = F)

# 
# ##"spring.mean.min.temp"   "prev_summer.tot.precip"
# gm.su.sp.p <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + prev_summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.p1 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + prev_summer.tot.precip + I(prev_summer.tot.precip^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.p2 <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + prev_summer.tot.precip + I(spring.mean.min.temp^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.trt.p <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp + trt + prev_summer.tot.precip+(1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.trt.int.p <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.min.temp*trt +prev_summer.tot.precip+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.su.sp.trt.int2.p <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip*trt +spring.mean.min.temp+ (1|Plot) + (1|Year), data = dac, REML = F)
# 
# ##"summer.tot.precip"      "prev_summer.tot.precip"
# gm.3.1 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + prev_summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.3.1.1 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + prev_summer.tot.precip + I(prev_summer.tot.precip^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.3.1.2 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + prev_summer.tot.precip + I(summer.tot.precip^2)+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.3.2 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + trt + prev_summer.tot.precip+(1|Plot) + (1|Year), data = dac, REML = F)
# gm.3.3 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip*trt +prev_summer.tot.precip+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.3.4 <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip*trt +summer.tot.precip+ (1|Plot) + (1|Year), data = dac, REML = F)
# 
# ##"prev_summer.tot.precip" "summer.mean.max.temp"  
# gm.4.1 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + prev_summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# gm.4.1.1 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + prev_summer.tot.precip +  I(prev_summer.tot.precip^2)+(1|Plot) + (1|Year), data = dac, REML = F)
# gm.4.1.2 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + prev_summer.tot.precip +  I(summer.mean.max.temp^2)+(1|Plot) + (1|Year), data = dac, REML = F)
# gm.4.2 <- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp + trt + prev_summer.tot.precip+(1|Plot) + (1|Year), data = dac, REML = F)
# gm.4.3<- lmer(log.no.stemsT1 ~ log.no.stems + summer.mean.max.temp*trt +prev_summer.tot.precip+ (1|Plot) + (1|Year), data = dac, REML = F)
# gm.4.4 <- lmer(log.no.stemsT1 ~ log.no.stems + prev_summer.tot.precip*trt +summer.mean.max.temp+ (1|Plot) + (1|Year), data = dac, REML = F)

################################################################################
###
growth <- mget(ls(pattern = "^gm")) #make a list of all of those models that start with gm (^ means start with)
growth_AICc<-aictab(cand.set = growth, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("gm", ls())]) #removes everything with gm

summary(gm.su.sp)
```

```{r save growth}
growth_AICc2 <- growth_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(growth, get_fixed_formula)

growth_AICc2$fixed_effects <- fixed_formulas[growth_AICc2$Modnames]


growth.d <- growth_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

growth.d %>% gt() %>% gtsave(here("Tables", "Dactylis", "Dactylis.AIC.table.growth.docx"))

#save the best fit model
summary(gm.su.sp)
coefs <- summary(gm.su.sp)$coefficients

g.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(g.coef, here("Tables", "Dactylis", "dactylis_growth_best_fit_coeff.csv"), row.names = F)
```



```{r growth figures}
pred.dat.g <- expand.grid(log.no.stems = seq(min(dac$log.no.stems, na.rm = TRUE), max(dac$log.no.stems, na.rm = TRUE), by = .1), summer.tot.precip = c(-1, 0, 1), spring.mean.min.temp = c(-1,0, 1))
pred.dat.output.g <- cbind(pred.dat.g, as.data.frame(predict(gm.su.sp, newdata = pred.dat.g, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.g)[ncol(pred.dat.output.g)] <- "log.no.stemsT1"  # Renaming the last column

(growth.sp <- dac %>%
  ggplot(aes(x = log.no.stems, y = log.no.stemsT1))+
  geom_point(data = dac ,alpha = 0.5, shape = 1)+
  geom_line(data = subset(pred.dat.output.g, summer.tot.precip == 0 & spring.mean.min.temp != 0), aes(color = factor(spring.mean.min.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.25, .9),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+  geom_abline(slope=1, intercept = 0, color= "grey", linewidth = .4)+
  scale_color_manual(name = "Spring temp, t", values = c("#00a3a3","#d72a96"), labels = c("Cool", "Warm")) +
  scale_y_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  labs(x = "log(Number of Stems) in t", y = "log(Number of Stems) in t + 1"))

(growth.su <- dac %>%
  ggplot(aes(x = log.no.stems, y = log.no.stemsT1))+
  geom_point(data = dac ,alpha = 0.5, shape = 1)+
  geom_line(data = subset(pred.dat.output.g, spring.mean.min.temp == 0 & summer.tot.precip !=0), aes(color = factor(summer.tot.precip)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.25, .9),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+  geom_abline(slope=1, intercept = 0, color= "grey", linewidth = .4)+
  scale_color_manual(name = "Summer precip, t", values = c("darkorange","deepskyblue"), labels = c("Dry", "Wet")) +
  scale_y_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  labs(x = "log(Number of Stems) in t", y = "log(Number of Stems) in t + 1"))

(gr.fig <- growth.sp+growth.su +  plot_annotation(tag_levels = 'i') + plot_layout(axes = "collect")
)
ggsave(here("Figures", "Dactylis", "growth.png"), plot = gr.fig, width = 10, height =6)
```


```{r pflower prequel}
base.p <- glmer(pflowerT ~ log.no.stems*Year + (1|Plot) , data = dac, family = "binomial", control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
drop1(base.p,test="Chisq") #nope interaction not significant
#
base.p2 <- glmer(pflowerT ~ log.no.stems+Year + (1|Plot) , data = dac, family = "binomial", control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
base.p3 <- glmer(pflowerT ~ log.no.stems+ (1|Plot), data = dac, family = "binomial")
a2 <- anova(base.p3, base.p2, test="LRT") #yes year is significant
best.pflower <- glmer(pflowerT ~ log.no.stems + (1|Year) + (1|Plot), data = dac, family = "binomial")

re_year <- rownames_to_column(
  as.data.frame(ranef(best.pflower)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year))%>% 
  rename(int = `(Intercept)`)

pflower.corr <- left_join(re_year, climate) %>% 
  select(-year)

# get correlations and p-values
cor_results <- lapply(names(pflower.corr), function(v) {
  test <- cor.test(pflower.corr$int, pflower.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_pflower <- do.call(rbind, cor_results)
cor_results_pflower$p_value <- format(cor_results_pflower$p_value, scientific = FALSE)

###
#these are the ones to test
#prev_spring.mean.temp
#prev_winter.mean.max.temp
vars <- c("prev_spring.mean.temp", "prev_winter.mean.max.temp")

# Unique climate-year values
dac.unique <- dac %>%
  distinct(Year, across(all_of(vars)))

# All pairwise combinations
pairs <- combn(vars, 2, simplify = FALSE)

cor_results <- map_dfr(pairs, function(p) {
  x <- dac.unique[[p[1]]]
  y <- dac.unique[[p[2]]]
  ct <- cor.test(x, y)
  tibble(
    var1 = p[1],
    var2 = p[2],
    estimate = unname(ct$estimate),
    statistic = unname(ct$statistic),
    p.value = ct$p.value,
    conf.low = ct$conf.int[1],
    conf.high = ct$conf.int[2]
  )
})

cor_results
pairs <- combn(vars, 2, simplify = FALSE)

pairs
#dont test [1] "prev_spring.mean.temp"     "prev_winter.mean.max.temp"///correlated
```

```{r pflower model selection}
fm.base.size <- glmer(pflowerT ~ log.no.stems + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.base.trt <- glmer(pflowerT ~ log.no.stems+ trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.base.trt.int <- glmer(pflowerT ~ log.no.stems*trt + (1|Plot) + (1|Year), data = dac, family = "binomial")

#grow season ave temp
fm.prev_spring.mean.temp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_spring.mean.tempq <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + I(prev_spring.mean.temp^2)+ (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_spring.mean.temp.trt <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_spring.mean.temptrt.int <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp*trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_spring.mean.temptrt.int2 <- glmer(pflowerT ~ log.no.stems*trt + prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_spring.mean.temptrt.int3 <- glmer(pflowerT ~ log.no.stems*trt + prev_spring.mean.temp*trt+ (1|Plot) + (1|Year), data = dac, family = "binomial")

#fm.prev_spring.mean.temptrt.int3 <- glmer(pflowerT ~ log.no.stems*prev_spring.mean.temp+ trt + (1|Plot) + (1|Year), data = dac, family = "binomial")


#prev_winter.mean.max.temp
fm.prev_winter.mean.temp <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_winter.mean.tempq <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + I(prev_winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_winter.mean.temp.trt <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_winter.mean.temp.trt.int1 <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp*trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_winter.mean.temp.trt.int2 <- glmer(pflowerT ~ log.no.stems*trt + prev_winter.mean.max.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.prev_winter.mean.temp.trt.int3 <- glmer(pflowerT ~ log.no.stems*trt + prev_winter.mean.max.temp*trt + (1|Plot) + (1|Year), data = dac, family = "binomial")

#fm.prev_winter.mean.temp.trt.int3 <- glmer(pflowerT ~ log.no.stems*prev_winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = dac, family = "binomial")

# # 
# #spring.tot.precip
# fm.spp <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.spp.q <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.spp.t <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.spp.ti1 <- glmer(pflowerT ~ log.no.stems + spring.tot.precip*trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.spp.ti2 <- glmer(pflowerT ~ log.no.stems*trt + spring.tot.precip+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# #fm.spp.ti3 <- glmer(pflowerT ~ log.no.stems*spring.tot.precip + trt +  (1|Plot) + (1|Year), data = dac, family = "binomial")
# 
# 
# #prev_winter.tot.precip
# fm.prev_winter.p <- glmer(pflowerT ~ log.no.stems + prev_winter.tot.precip + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.prev_winter.pq <- glmer(pflowerT ~ log.no.stems + prev_winter.tot.precip + I(prev_winter.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.prev_winter.p.trt <- glmer(pflowerT ~ log.no.stems + prev_winter.tot.precip + trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.prev_winter.p.trt.int1 <- glmer(pflowerT ~ log.no.stems + prev_winter.tot.precip*trt + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.prev_winter.p.trt.int2 <- glmer(pflowerT ~ log.no.stems*trt + prev_winter.tot.precip + (1|Plot) + (1|Year), data = dac, family = "binomial")
# #fm.prev_winter.p.trt.int3 <- glmer(pflowerT ~ log.no.stems*prev_winter.tot.precip +trt +  (1|Plot) + (1|Year), data = dac, family = "binomial")
# 
# # 
# "prev_winter.tot.precip" "spring.tot.precip"  
# fm.wt.sp.p <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + prev_winter.tot.precip + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.pq1 <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + prev_winter.tot.precip + I(prev_winter.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.pq2 <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + prev_winter.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.p <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + trt + prev_winter.tot.precip+(1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.int.p <- glmer(pflowerT ~ log.no.stems + spring.tot.precip*trt +prev_winter.tot.precip+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.int2.p <- glmer(pflowerT ~ log.no.stems + prev_winter.tot.precip*trt +spring.tot.precip+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# 
# # "prev_winter.mean.max.temp" "spring.tot.precip"  
# fm.wt.sp.p.tp <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + prev_winter.mean.max.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.p.tpq1 <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + prev_winter.mean.max.temp + I(prev_winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.p.tpq2 <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + prev_winter.mean.max.temp + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.p.tp <- glmer(pflowerT ~ log.no.stems + spring.tot.precip + trt + prev_winter.mean.max.temp+(1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.int.p.tp <- glmer(pflowerT ~ log.no.stems + spring.tot.precip*trt +prev_winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.int2.p.tp <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp*trt +spring.tot.precip+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# 
# # "prev_spring.mean.temp" "spring.tot.precip"
# fm.st.sp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.st.spq1 <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.st.spq2 <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + spring.tot.precip + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.st.sp.trt <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + trt + spring.tot.precip+(1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.st.sp.trt.int <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp*trt +spring.tot.precip+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.st.sp.trt.int2 <- glmer(pflowerT ~ log.no.stems + spring.tot.precip*trt +prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# 
# # #"prev_spring.mean.temp"  "prev_winter.tot.precip"
# fm.wt.sp.tp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + prev_winter.tot.precip + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.tpq1 <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + prev_winter.tot.precip + I(prev_winter.tot.precip^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.tpq2 <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + prev_winter.tot.precip + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.tp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + trt + prev_winter.tot.precip+(1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.int.tp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp*trt +prev_winter.tot.precip+ (1|Plot) + (1|Year), data = dac, family = "binomial")
# fm.wt.sp.trt.int2.tp <- glmer(pflowerT ~ log.no.stems + prev_winter.tot.precip*trt +prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")

#"prev_winter.mean.max.temp" "prev_winter.tot.precip"   
fm.wt.wp.tp <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.tpq1 <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + prev_spring.mean.temp + I(prev_winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.tpq2 <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + prev_spring.mean.temp + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.trt.tp <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp + trt + prev_spring.mean.temp+(1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.trt.int.tp <- glmer(pflowerT ~ log.no.stems + prev_winter.mean.max.temp*trt +prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.trt.int2.tp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp*trt +prev_winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.trt.int3.tp <- glmer(pflowerT ~ log.no.stems*trt + prev_spring.mean.temp +prev_winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac, family = "binomial")
fm.wt.wp.trt.int4.tp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp*trt +prev_winter.mean.max.temp*trt+ (1|Plot) + (1|Year), data = dac, family = "binomial")

################################################################################
###
pflower <- mget(ls(pattern = "^fm")) #make a list of all of those models that start with gm (^ means start with)
pflower_AICc<-aictab(cand.set = pflower, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("fm", ls())]) #removes everything with gm

summary(fm.prev_spring.mean.tempq)
```

```{r save pflower}
pflower_AICc2 <- pflower_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(pflower, get_fixed_formula)

pflower_AICc2$fixed_effects <- fixed_formulas[pflower_AICc2$Modnames]


flower.d <- pflower_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

flower.d %>% gt() %>% gtsave(here("Tables", "Dactylis", "Dactylis.AIC.table.pflower.docx"))

#save the best fit model
summary(fm.prev_spring.mean.tempq)
coefs <- summary(fm.prev_spring.mean.tempq)$coefficients

f.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(f.coef, here("Tables", "Dactylis","dactylis_pflower_best_fit_coeff.csv"), row.names = F)
```

```{r pflower figure}
pred.dat.p <- expand.grid(log.no.stems = seq(min(dac$log.no.stems, na.rm = TRUE), max(dac$log.no.stems, na.rm = TRUE), by = .1), prev_spring.mean.temp = c(-1, 1))
pred.dat.output.p <- cbind(pred.dat.p, as.data.frame(predict(fm.prev_spring.mean.tempq, newdata = pred.dat.p, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.p)[ncol(pred.dat.output.p)] <- "pflowerT"  # Renaming the last column

# # 
(flower <- dac %>%
  ggplot(aes(x = log.no.stems, y = as.numeric(pflowerT)-1))+
  geom_jitter(data = dac ,alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = pred.dat.output.p, aes(y = pflowerT, color = as.character(prev_spring.mean.temp)),linewidth = 1.5) +
  scale_color_manual(name = "Spring temp, t-1", values = c("#00a3a3","#d72a96"), labels = c("Cool", "Warm")) +
  labs(x = "log(Number of Stems) in t", y = "Probability of Flowering in t")+
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.85, .25),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA)))

ggsave(here("Figures", "Dactylis", "flower.png"), plot = flower, width = 6, height =6)
```

_Survival_
```{r survival prequel}
# dac.survival <- dac %>% 
#   filter(Year!= "2024",
#          Year!= "2025")
table(dac.surv$survT1, dac.surv$Year)
base.s <- glmer(survT1 ~ log.no.stems*Year + (1|Plot) , data = dac.surv, family = "binomial", control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
drop1(base.s,test="Chisq") #yes, keep size*climate interactions

best.s <- glmer(survT1 ~ log.no.stems + (1|Year) + (1|Plot) , data = dac.surv, family = "binomial")

re_year <- rownames_to_column(
  as.data.frame(ranef(best.s)$Year),
  var = "Year") %>% 
  mutate(year = as.numeric(Year))%>% 
  rename(int = `(Intercept)`)

surv.corr <- left_join(re_year, climate) %>% 
  select(-Year)

# get correlations and p-values
cor_results <- lapply(names(surv.corr), function(v) {
  test <- cor.test(surv.corr$int, surv.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value)
})
# Combine into one data frame
cor_results_surv <- do.call(rbind, cor_results)


#prev_spring.mean.temp, spring.tot.precip, winter.mean.max.temp
#these are the ones to test
vars <- c( "prev_spring.mean.temp", "winter.mean.max.temp",
          "spring.tot.precip")

# Unique climate-year values from dac.surv
dac.surv.unique <- dac.surv %>%
  distinct(Year, across(all_of(vars)))

# All pairwise combinations
pairs <- combn(vars, 2, simplify = FALSE)

cor_results <- map_dfr(pairs, function(p) {
  x <- dac.surv.unique[[p[1]]]
  y <- dac.surv.unique[[p[2]]]
  ct <- cor.test(x, y)
  tibble(
    var1 = p[1],
    var2 = p[2],
    estimate = unname(ct$estimate),
    statistic = unname(ct$statistic),
    p.value = ct$p.value,
    conf.low = ct$conf.int[1],
    conf.high = ct$conf.int[2]
  )
})

cor_results

pairs <- combn(vars, 2, simplify = FALSE)

pairs
#dont test: "prev_fall.tot.precip" "spring.tot.precip" ' 
#"summer.mean.temp"      "prev_spring.mean.temp"

```

```{r survival model selection}
sm.base.size <- glmer(survT1 ~ log.no.stems + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.base.trt <- glmer(survT1 ~ log.no.stems+ trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.base.trt.int <- glmer(survT1 ~ log.no.stems*trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

#grow season ave temp
sm.prev_spring.mean.temp <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temp.q <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temp.trt <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temptrt.int <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp*trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temptrt.int2 <- glmer(survT1 ~ log.no.stems*trt + prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temptrt.int3 <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + trt+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.mean.temptrt.int4 <- glmer(survT1 ~ log.no.stems*trt +prev_spring.mean.temp* trt+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

#prev.winter
sm.winter.mean.max.temp <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.q <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + I(winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.int <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.trt <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.trt.int <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp*trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.trt.int2 <- glmer(survT1 ~ log.no.stems*trt + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.trt.int3 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + trt +  (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.winter.mean.max.temp.trt.int4 <- glmer(survT1 ~ log.no.stems*trt + winter.mean.max.temp*trt +  (1|Plot) + (1|Year), data = dac.surv, family = "binomial")


#spring tot precip
sm.prev_spring.p <- glmer(survT1 ~ log.no.stems + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.pq <- glmer(survT1 ~ log.no.stems + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.p.int <- glmer(survT1 ~ log.no.stems*spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.p.trt <- glmer(survT1 ~ log.no.stems + spring.tot.precip + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.ptrt.int <- glmer(survT1 ~ log.no.stems + spring.tot.precip*trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.ptrt.int2 <- glmer(survT1 ~ log.no.stems*trt + spring.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.ptrt.int3 <- glmer(survT1 ~ log.no.stems*spring.tot.precip+trt +  (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.prev_spring.ptrt.int3 <- glmer(survT1 ~ log.no.stems*trt +spring.tot.precip*trt +  (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

#fall
# sm.fall.p <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fall.pq <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + I(prev_fall.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fall.p.int <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fall.p.trt <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fall.p.trt.int <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip*trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fall.p.trt.int2 <- glmer(survT1 ~ log.no.stems*trt + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fall.p.trt.int3 <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# 
# 
# #summer.mean.temp
# sm.summer.mean.temp <- glmer(survT1 ~ log.no.stems + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.summer.mean.tempq <- glmer(survT1 ~ log.no.stems + summer.mean.temp + I(summer.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.summer.mean.temp.int <- glmer(survT1 ~ log.no.stems*summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.summer.mean.temp.trt <- glmer(survT1 ~ log.no.stems + summer.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.summer.mean.temp.trt.int <- glmer(survT1 ~ log.no.stems + summer.mean.temp*trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.summer.mean.temp.trt.int2 <- glmer(survT1 ~ log.no.stems*trt + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.summer.mean.temp.trt.int3 <- glmer(survT1 ~ log.no.stems*summer.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# 
# 
# # summer.mean.temp – prev_fall.tot.precip
# sm.sfp <- glmer(survT1 ~ log.no.stems + summer.mean.temp + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfp.q1 <- glmer(survT1 ~ log.no.stems + summer.mean.temp + prev_fall.tot.precip + I(summer.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfp.q2 <- glmer(survT1 ~ log.no.stems + summer.mean.temp + prev_fall.tot.precip + I(prev_fall.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfp.int <- glmer(survT1 ~ log.no.stems*summer.mean.temp + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfp.int2 <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfptrt <- glmer(survT1 ~ log.no.stems + summer.mean.temp + trt + prev_fall.tot.precip+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# #sm.sfptrt.int <- glmer(survT1 ~ log.no.stems + summer.mean.temp*trt +prev_fall.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfptrt.int2 <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip*trt +summer.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfptrt.int3 <- glmer(survT1 ~ log.no.stems*summer.mean.temp+trt+prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfptrt.int4 <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + summer.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sfp.trt.int6 <- glmer(survT1 ~ log.no.stems*trt + prev_fall.tot.precip + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# 
# # summer.mean.temp – winter.mean.max.temp
# sm.w <- glmer(survT1 ~ log.no.stems + summer.mean.temp + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.w.q1 <- glmer(survT1 ~ log.no.stems + summer.mean.temp + winter.mean.max.temp + I(summer.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.w.q2 <- glmer(survT1 ~ log.no.stems + summer.mean.temp + winter.mean.max.temp + I(winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.w.int <- glmer(survT1 ~ log.no.stems*summer.mean.temp + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.w.int2 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.wtrt <- glmer(survT1 ~ log.no.stems + summer.mean.temp + trt + winter.mean.max.temp+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.wtrt.int <- glmer(survT1 ~ log.no.stems + summer.mean.temp*trt +winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.wtrt.int2 <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp*trt +summer.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.wtrt.int3 <- glmer(survT1 ~ log.no.stems*summer.mean.temp+trt+winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.wtrt.int4 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + summer.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.w.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+winter.mean.max.temp + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

# # summer.mean.temp – spring.tot.precip
# sm.sp <- glmer(survT1 ~ log.no.stems + summer.mean.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sp.q1 <- glmer(survT1 ~ log.no.stems + summer.mean.temp + spring.tot.precip + I(summer.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sp.q2 <- glmer(survT1 ~ log.no.stems + summer.mean.temp + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sp.int <- glmer(survT1 ~ log.no.stems*summer.mean.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sp.int2 <- glmer(survT1 ~ log.no.stems*spring.tot.precip + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sptrt <- glmer(survT1 ~ log.no.stems + summer.mean.temp + trt + spring.tot.precip+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sptrt.int <- glmer(survT1 ~ log.no.stems + summer.mean.temp*trt +spring.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sptrt.int2 <- glmer(survT1 ~ log.no.stems + spring.tot.precip*trt +summer.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sptrt.int3 <- glmer(survT1 ~ log.no.stems*summer.mean.temp+trt+spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sptrt.int4 <- glmer(survT1 ~ log.no.stems*spring.tot.precip + summer.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sp.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+spring.tot.precip + summer.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

# # prev_spring.mean.temp – prev_fall.tot.precip
# sm.sppt <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.spptq1 <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + prev_fall.tot.precip + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.spptq2 <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + prev_fall.tot.precip + I(prev_fall.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppt.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppt.int2 <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppttrt <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + trt + prev_fall.tot.precip+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppttrt.int <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp*trt +prev_fall.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppttrt.int2 <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip*trt +prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppttrt.int3 <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp+trt+prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppttrt.int4 <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + prev_spring.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.sppt.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+prev_fall.tot.precip + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

# prev_spring.mean.temp – winter.mean.max.temp
sm.wt.sp <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.spq1 <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + winter.mean.max.temp + I(winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.spq2 <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + winter.mean.max.temp  + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.int2 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.trt <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + trt + winter.mean.max.temp+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.trt.int <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp*trt + winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.trt.int2 <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp*trt +prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.trt.int3 <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp+trt+winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.trt.int4 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + prev_spring.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.wt.sp.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+winter.mean.max.temp + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

# prev_spring.mean.temp – spring.tot.precip
sm.ss <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.spq1 <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.spq2 <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + spring.tot.precip  + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.int2 <- glmer(survT1 ~ log.no.stems*spring.tot.precip + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.trt <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp + trt + spring.tot.precip+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.trt.int <- glmer(survT1 ~ log.no.stems + prev_spring.mean.temp*trt +spring.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.trt.int2 <- glmer(survT1 ~ log.no.stems + spring.tot.precip*trt +prev_spring.mean.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.trt.int3 <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp+trt+spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.trt.int4 <- glmer(survT1 ~ log.no.stems*spring.tot.precip + prev_spring.mean.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.ss.sp.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+spring.tot.precip + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

# prev_fall.tot.precip – winter.mean.max.temp
# sm.fw <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.spq1 <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + winter.mean.max.temp + I(winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.spq2 <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + winter.mean.max.temp  + I(prev_fall.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.int <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.int2 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.trt <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip + trt + winter.mean.max.temp+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.trt.int <- glmer(survT1 ~ log.no.stems + prev_fall.tot.precip*trt +winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.trt.int2 <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp*trt +prev_fall.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.trt.int3 <- glmer(survT1 ~ log.no.stems*prev_fall.tot.precip+trt+winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.trt.int4 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + prev_fall.tot.precip + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# sm.fw.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+winter.mean.max.temp + prev_fall.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

# winter.mean.max.temp – spring.tot.precip
sm.s <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.s.q1 <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + spring.tot.precip + I(winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.s.q2 <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.s.int <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp + spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.s.int2 <- glmer(survT1 ~ log.no.stems*spring.tot.precip + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.strt <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp + trt + spring.tot.precip+(1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.strt.int <- glmer(survT1 ~ log.no.stems + winter.mean.max.temp*trt +spring.tot.precip+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.strt.int2 <- glmer(survT1 ~ log.no.stems + spring.tot.precip*trt +winter.mean.max.temp+ (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.strt.int3 <- glmer(survT1 ~ log.no.stems*winter.mean.max.temp+trt+spring.tot.precip + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.strt.int4 <- glmer(survT1 ~ log.no.stems*spring.tot.precip + winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
sm.s.trt.int6 <- glmer(survT1 ~ log.no.stems*trt+spring.tot.precip + winter.mean.max.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

################################################################################
###
surv <- mget(ls(pattern = "^sm"))

# check convergence for each model (leaves singular fits in)
converged <- sapply(surv, function(m) {
  msgs <- m@optinfo$conv$lme4$messages
  # no messages at all -> fine
  if (is.null(msgs)) return(TRUE)
  # only messages present are singular-fit warnings -> still fine
  all(grepl("singular", msgs, ignore.case = TRUE))
})

# keep only converged models
surv_ok <- surv[converged]

# see which ones got dropped, if any
names(surv)[!converged]

surv_AICc <- aictab(cand.set = surv_ok, modnames = names(surv_ok), second.ord = TRUE, nobs = NULL, sort = TRUE)
#rm(list = ls()[grepl("sm", ls())]) #removes everything with gm
```

```{r save survival}
surv_AICc2 <- surv_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(surv_ok, get_fixed_formula)

surv_AICc2$fixed_effects <- fixed_formulas[surv_AICc2$Modnames]


survival.d <- surv_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

survival.d %>% gt() %>% gtsave(here("Tables", "Dactylis.AIC.table.survival.docx"))

#save the best fit model
summary(sm.wt.sp.int)
coefs <- summary(sm.wt.sp.int)$coefficients

s.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(s.coef, here("Tables", "dactylis_survival_best_fit_coeff.csv"), row.names = F)
```


```{r surv figure}
pred.dat.s <- expand.grid(log.no.stems = seq(min(dac$log.no.stems, na.rm = TRUE), max(dac$log.no.stems, na.rm = TRUE), by = .1), prev_spring.mean.temp = c(-1, 0, 1), winter.mean.max.temp = c(-1, 0, 1))
pred.dat.output.s <- cbind(pred.dat.s, as.data.frame(predict(sm.wt.sp.int, newdata = pred.dat.s, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.s)[ncol(pred.dat.output.s)] <- "survT1"  # Renaming the last column

(s.sp <- 
  dac.surv %>% 
  ggplot(aes(x = log.no.stems, y = as.numeric(survT1)-1))+
  geom_jitter(alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = subset(pred.dat.output.s, winter.mean.max.temp == 0 & prev_spring.mean.temp != 0), aes(y = survT1, color = factor(prev_spring.mean.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.85, .25),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+  
    scale_color_manual(name = "Spring temp, t-1", values = c("#00a3a3","#d72a96"), labels = c("cool", "warm")) +
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  labs(x = "log(Number of Stems) in t", y = "Survival in t + 1"))

(s.su <- dac.surv %>% 
  ggplot(aes(x = log.no.stems, y = as.numeric(survT1)-1))+
  geom_jitter(alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = subset(pred.dat.output.s, prev_spring.mean.temp == 0 & winter.mean.max.temp !=0), aes(y = survT1, color = factor(winter.mean.max.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.85, .25),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+  
    scale_color_manual(name = "Winter temp, t", values = c("#90d4cc", "#bd3027"), labels = c("cool", "warm")) +
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  labs(x = "log(Number of Stems) in t", y = "Survival in t + 1"))

(s.fig <- s.sp+s.su +  plot_annotation(tag_levels = 'i') + plot_layout(axes = "collect")
)
ggsave(here("Figures", "Dactylis", "survival.png"), plot = s.fig, width = 10, height =6)
```

_panicles_
```{r panicles prequel}

base.pan <- glmer(No.panicles ~ log.no.stems+Year + (1|Plot) , data = subset(dac, pflowerT == "1"), family = "poisson")
drop1(base.pan,test="Chisq") #no size*climate interactions

poisson.base.size <- glmer(No.panicles ~ log.no.stems + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")

re_year <- rownames_to_column(
  as.data.frame(ranef(poisson.base.size)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year)) %>% 
    rename(int = `(Intercept)`)

pan.corr <- left_join(re_year, climate) %>% 
  select(-year)

# get correlations and p-values
cor_results <- lapply(names(pan.corr), function(v) {
  test <- cor.test(pan.corr$int, pan.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_pan <- do.call(rbind, cor_results)


#prev_spring.mean.max.temp
#prev_winter.tot.precip
# #these are the ones to test
# vars <- c("prev_spring.mean.max.temp", "prev_winter.tot.precip")
# 
# # Unique climate-year values
# dac.unique <- dac %>%
#   filter( pflowerT == "1") |> 
#   distinct(Year, across(all_of(vars)))
# 
# # All pairwise combinations
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# cor_results <- map_dfr(pairs, function(p) {
#   x <- dac.unique[[p[1]]]
#   y <- dac.unique[[p[2]]]
#   ct <- cor.test(x, y)
#   tibble(
#     var1 = p[1],
#     var2 = p[2],
#     estimate = unname(ct$estimate),
#     statistic = unname(ct$statistic),
#     p.value = ct$p.value,
#     conf.low = ct$conf.int[1],
#     conf.high = ct$conf.int[2]
#   )
# })
# 
# cor_results
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# pairs

```


```{r panicles model selection}

nb.base.size <- glmer.nb(No.panicles ~ log.no.stems + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.base.trt <- glmer.nb(No.panicles ~ log.no.stems + trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.base.trt.int <- glmer.nb(No.panicles ~ log.no.stems*trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))

## prev_spring.mean.max.temp
nb.prev_spring.mean.temp <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.max.temp + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.prev_spring.mean.temp.q <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.max.temp + I(prev_spring.mean.max.temp^2) + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.prev_spring.mean.temp.trt <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.max.temp + trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.prev_spring.mean.temp.trt.int2 <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.max.temp*trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.prev_spring.mean.temp.trt.int3 <- glmer.nb(No.panicles ~ log.no.stems*trt + prev_spring.mean.max.temp + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
nb.prev_spring.mean.temp.trt.int4 <- glmer.nb(No.panicles ~ log.no.stems*trt + prev_spring.mean.max.temp*trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))

# ## prev_winter.tot.precip
# nb.prev_winter.tot.precip <- glmer.nb(No.panicles ~ log.no.stems + prev_winter.tot.precip + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.prev_winter.tot.precip.q <- glmer.nb(No.panicles ~ log.no.stems + prev_winter.tot.precip + I(prev_winter.tot.precip^2) + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.prev_winter.tot.precip.trt <- glmer.nb(No.panicles ~ log.no.stems + prev_winter.tot.precip + trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.prev_winter.tot.precip.trt.int2 <- glmer.nb(No.panicles ~ log.no.stems + prev_winter.tot.precip*trt + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.prev_winter.tot.precip.trt.int3 <- glmer.nb(No.panicles ~ log.no.stems*trt + prev_winter.tot.precip + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# 
# ## both
# nb.sp.wt.temp <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.temp + prev_winter.tot.precip + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.sp.wt.temp.q1 <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.temp + prev_winter.tot.precip + I(prev_winter.tot.precip^2) + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.sp.wt.temp.q2 <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.temp + prev_winter.tot.precip + I(prev_spring.mean.temp^2) + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.sp.wt.trt <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.temp + trt + prev_winter.tot.precip + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.sp.wt.trt.int2 <- glmer.nb(No.panicles ~ log.no.stems + prev_spring.mean.temp*trt + prev_winter.tot.precip + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.sp.wt.trt2 <- glmer.nb(No.panicles ~ log.no.stems + prev_winter.tot.precip + trt + prev_spring.mean.temp + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))
# nb.sp.wt.trt.int4 <- glmer.nb(No.panicles ~ log.no.stems + prev_winter.tot.precip*trt + prev_spring.mean.temp + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"))

################################################################################
###
panicles <- mget(ls(pattern = "^nb")) #make a list of all of those models that start with gm (^ means start with)
panicles_AICc<-aictab(cand.set = panicles, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)


# }
# overdisp_fun <- function(model) {
#   rdf <- df.residual(model)
#   rp <- residuals(model, type = "pearson")
#   Pearson.chisq <- sum(rp^2)
#   prat <- Pearson.chisq / rdf
#   pval <- pchisq(Pearson.chisq, df = rdf, lower.tail = FALSE)
# 
#   c(
#     chisq = Pearson.chisq,
#     ratio = prat,
#     rdf = rdf,
#     p = pval
#   )
# }
# overdisp_fun(poisson.prev_spring.mean.temp.q)


summary(nb.prev_spring.mean.temp.q)
```


```{r save panciles}
panicles_AICc2 <- panicles_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(panicles, get_fixed_formula)

panicles_AICc2$fixed_effects <- fixed_formulas[panicles_AICc2$Modnames]


pan.d <- panicles_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

pan.d %>% gt() %>% gtsave(here("Tables", "Dactylis.AIC.table.panicles.docx"))

#save the best fit model
summary(sm.wt.sp.int)
coefs <- summary(sm.wt.sp.int)$coefficients

p.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(p.coef, here("Tables", "dactylis_panicles_best_fit_coeff.csv"), row.names = F)
```


```{r number panicles figure}
pred.dat.pan <- expand.grid(log.no.stems = seq(min(dac$log.no.stems, na.rm = TRUE), max(dac$log.no.stems, na.rm = TRUE), by = .1), prev_spring.mean.max.temp = c(-1, 1))
pred.dat.output.pan <- cbind(pred.dat.pan, as.data.frame(predict(nb.prev_spring.mean.temp.q, newdata = pred.dat.pan, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.pan)[ncol(pred.dat.output.pan)] <- "No.panicles"  # Renaming the last column

# (flowering <- dac %>% 
#   ggplot(aes(x = log.no.stems, y = pflowerT))+
#   geom_point(aes(data = dac ,alpha = 0.5, size = summer.tot.precip), shape = 1)+
#   #geom_line(data = subset(pred.dat.output.g, summer.tot.precip == 0), aes(x = log.no.stems, y = pflowerT), color = "grey", size = 1.5)+ 
#   geom_line(data = subset(pred.dat.output.g, summer.tot.precip == 1), aes(x = log.no.stems, y = pflowerT), color = "lightblue", size = 1.5)+ 
#   geom_line(data = subset(pred.dat.output.g, summer.tot.precip == -1), aes(x = log.no.stems, y = pflowerT), color = "orange", size = 1.5)+ 
#   theme(axis.line = element_line(colour = 'black', linewidth = 1.1))+
#   geom_abline(slope=1, intercept = 0, color= "grey", linewidth = .2)+
#   scale_y_continuous(expand = c(0, 0), limits = c(-.25, 5))+
#   scale_x_continuous(expand = c(0, 0), limits = c(-.25, 5))+
#   labs( x = "log(Number of Stems) in t", y = "log(Number of Stems) in t + 1"))

(pan.fig <- dac %>% 
  filter(pflowerT == "1") %>% 
  ggplot(aes(x = log.no.stems, y = No.panicles))+
  geom_jitter(alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = pred.dat.output.pan, aes(y = No.panicles, color = factor(prev_spring.mean.max.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.25, 0.8),   legend.background = element_rect(fill = NA, colour = NA),
  legend.key = element_rect(fill = NA, colour = NA))+   scale_color_manual(name = "Spring temp, t-1", values = c("#00a3a3","#d72a96"), labels = c("cool", "warm")) +
  labs(x = "log(Number of Stems) in t", y = "Number of panicles in t"))


ggsave(here("Figures", "Dactylis", "pan.png"), plot = pan.fig, width = 10, height =6)

```
Spring:
"#00a3a3","#d72a96"
winter:
"#0c74ce","#a30031"
summer: "#89d3d6","#f69338"
summer precip:
"darkorange","deepskyblue"

```{r}


(
all <- (growth.sp + growth.su  + s.sp + s.su + flower+ pan.fig) +
  plot_layout(ncol = 2, axis_titles = "collect") +
  plot_annotation(tag_levels = "A", tag_suffix = ")") &
  theme(
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 10),
    legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA)
  ))
ggsave(here("Figures", "Dactylis", "all.png"), plot = all, width = 10, height =15)


```

