---
title: "dactylis.ipm"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---

```{r packages}
## Primula vital rates with climate data
library(here)
library(tidyverse)
library(AICcmodavg)
library(lme4)
library(patchwork) #for putting plots into one
library(popbio)
theme_set(theme_classic(base_size = 18)) #for ggplot
```
test
```{r}
dac <- read.csv(here("clean_data", "Dactylis_Demography_Data_CLEANED_2016thru2026.csv"))
climate <- read.csv(here("clean_data", "CGOP_climatevalues_scaled.csv"))
climate<- climate %>%
  arrange(year) %>%
  mutate(across(-year, ~lag(.x), .names = "prev_{.col}"))

future.climate <- read.csv(here("clean_data", "CGOP_future_climate_values.csv"))
# future.climate <- future.climate %>%
#   select(variable, future1, future2) %>%
#   pivot_wider(
#     names_from = variable,
#     values_from = c(future1, future2),
#     names_glue = "{variable}_{.value}"
#   )


dac <- left_join(dac, climate, by = c("Year" = "year"))
dac <- dac %>% 
  mutate(Year = as.factor(Year), 
         Plot = as.factor(Plot),
         survT = as.factor(survT),
         survT1 = as.factor(survT1),
         pflowerT = as.factor(pflowerT),
         pflowerT1 = as.factor(pflowerT1),
         log.no.stems = log(No.stems),
         log.no.stemsT1 = log(No.stemsT1),
        trt = as.factor(trt),
        trt = fct_relevel(trt, "irrigated", "control", "drought"))

dac <- dac %>% 
  filter(!(Plot %in% c("4", "5", "15")))

dac.surv <- dac %>% 
  filter(!Year =="2026",
  !is.na(survT1)) 

# gm.summer.p <- lmer(log.no.stemsT1 ~ log.no.stems + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# fm.prev_spring.mean.temp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
# sm.wt.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + winter.mean.min.temp + (1|Plot) + (1|Year), data = dac.survival, family = "binomial")
# # poisson.prev_spring.mean.temp.int <- glmer(No.panicles ~ log.no.stems *prev_spring.mean.temp + (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")
# gm.su.sp <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.temp + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
# 
# fm.prev_spring.mean.temp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
# 
# sm.wt.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + winter.mean.min.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
# 
# poisson.sp.wt.int2 <- glmer(No.panicles ~ log.no.stems*prev_winter.tot.precip + prev_spring.mean.temp+ (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")
gm.su.sp <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.temp + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
fm.prev_spring.mean.temp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
sm.wt.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + winter.mean.min.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")
poisson.sp.wt.int2 <- glmer(No.panicles ~ log.no.stems*prev_winter.tot.precip + prev_spring.mean.temp+ (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")

dac.new <- dac %>% 
  filter(stage == "seedling" & No.stems<2) %>% 
  group_by(plantid) %>%
  slice_min(as.numeric(as.character(Year)), n = 1, with_ties = FALSE)
#parameters for new plants
new_sd <- sd(dac.new$log.no.stems)
new_mean <- mean(dac.new$log.no.stems, na.rm = T)
hist(dac.new$log.no.stems)

#Define the min and max size, which are the integration bounds of the IPM.
minRealsize <- min(dac$log.no.stems, na.rm=T) 
maxRealsize <- 1.1* max(dac$log.no.stems,na.rm=T)

#now add a new min & max size to keep the plants in for eviction
## min size is 1 stem! cant be smaller
min.size <-minRealsize #lower
max.size <-maxRealsize+1.5 #upper

climate <- climate %>% 
  mutate(year = as.factor(year)) %>% 
  filter(year != "2015")
```

```{r}
#pancile to seedlings proxy:
#panciles in year t is a function of the number of panicles in the plot in the year prior
#so to get the transition rate: number of seedlings in t/#panciles year t-1 (PER PLOT - for now)
plot_summary <- dac %>%

  group_by(Plot, Year) %>%
  summarise(
    seedlings_t = sum(stage == "seedling" & No.stems < 2, na.rm = TRUE),
    panicles_t = sum(No.panicles, na.rm = TRUE),
    .groups = "drop") %>% 
  drop_na()
plot_summary <- plot_summary %>% 
  arrange(Plot, Year) %>%
  group_by(Plot) %>%
  mutate(panicles_tminus1 = lag(panicles_t)) %>%
  drop_na() %>% 
 # ungroup() %>% 
  mutate(germ.rate = seedlings_t/panicles_tminus1) %>% 
  filter(is.finite(germ.rate),
         Year!=2019)%>%
  group_by(Year) %>%
  summarise(
    mean_germ = mean(germ.rate, na.rm = TRUE),
    median_germ = median(germ.rate, na.rm = TRUE),
    sd_germ = sd(germ.rate, na.rm = TRUE),
    pest = sum(seedlings_t) / sum(panicles_tminus1),
    seedlingst = sum(seedlings_t),
    panicles_tminus1 = sum(panicles_tminus1),
    n = n(),
    .groups = "drop"
  ) |> 
  select(Year, pest) |> 
  filter(Year != "2026")
mean_est <- mean(plot_summary$pest, na.rm = TRUE)

pest <- bind_rows(
  tibble(
    Year = c("2016", "2019"),
    pest = c(mean_est, mean_est)
  ),
  plot_summary
) %>%
  arrange(Year)

#pest <- .0001
# 
# pest.sd <- sd(plot_summary$germ.rate)
# min(plot_summary$germ.rate)
# max(plot_summary$germ.rate)
#this is coarse! But ok for the first stab
```

```{r parameters}
#this is for range of climates spring.mean.temp, prev_spring.mean.temp, summer.tot.precip, winter.mean.min.temp, prev_winter.tot.precip

# rows <- expand.grid(summer.tot.precip = seq(-2, 2, by = 1), prev_spring.mean.temp = seq(-2, 2, by = 1),  spring.mean.temp = seq(-2, 2, by = 1),prev_winter.tot.precip = seq(-2, 2, by = 1),winter.mean.min.temp = seq(-2, 2, by = 1)) 

rows <- climate %>% 
  rename(Year = year) %>% 
  select(Year, spring.mean.temp, prev_spring.mean.temp, summer.tot.precip, winter.mean.min.temp, prev_winter.tot.precip)
#set up an empty parameter df
params=data.frame(
	growth.int = c(NA),
	growth.slope  = NA,
	growth.sd=NA,
	surv.int=NA,
	surv.slope=NA,
	pflow.int = NA,
	pflow.slope = NA,
	no.flow.int=NA,
	no.flow.slope=NA,
	recruit.size.mean=NA,
	recruit.size.sd=NA
)
params <- bind_cols(params, rows)

scenarios <- expand.grid(scenario = c("current", "future.precip", "future.temp", "future"))
params <- crossing(params, scenarios)

#add in the future climate variables
climate_vars <- future.climate$variable

for (v in climate_vars) {

  # Skip variables not present in params
  if (v %in% names(params)) {

    delta.precip <- future.climate$future.precip[future.climate$variable == v]
    delta.temp <- future.climate$future.temp[future.climate$variable == v]
    delta <- future.climate$future[future.climate$variable == v]


    params[[v]] <- case_when(
      params$scenario == "current" ~ params[[v]],
      params$scenario == "future.precip" ~ params[[v]] + delta.precip,
      params$scenario == "future.temp" ~ params[[v]] + delta.temp,
      params$scenario == "future" ~ params[[v]] + delta
    )
  }

  # Update corresponding prev_ variable if it exists
  prev_v <- paste0("prev_", v)

  if (prev_v %in% names(params)) {

    delta.precip <- future.climate$future.precip[future.climate$variable == v]
    delta.temp <- future.climate$future.temp[future.climate$variable == v]
    delta <- future.climate$future[future.climate$variable == v]

    params[[prev_v]] <- case_when(
      params$scenario == "current" ~ params[[prev_v]],
      params$scenario == "future.precip" ~ params[[prev_v]] + delta.precip,
      params$scenario == "future.temp" ~ params[[prev_v]] + delta.temp,
      params$scenario == "future" ~ params[[prev_v]] + delta
    )
  }
}

#adding in random effects
#growth
re_year_growth <- ranef(gm.su.sp)$Year %>%
  rownames_to_column(var = "Year") %>%
  rename(growth_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_growth, by = "Year") #%>% 
  #filter(!is.na(growth_re))

#pflower
re_year_pflower <- ranef(fm.prev_spring.mean.temp)$Year %>%
  rownames_to_column(var = "Year") %>%
  rename(pflower_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_pflower, by = "Year") 

#survival
re_year_surv <- ranef(sm.wt.sp.int)$Year %>%
  rownames_to_column(var = "Year") %>%
  rename(surv_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_surv, by = "Year") 

#no panciles
re_year_no.flow <- ranef(poisson.sp.wt.int2)$Year %>%
  rownames_to_column(var = "Year") %>%
  rename(no.flow_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_no.flow, by = "Year") 

### add in a average year for the SSD for the projections
climate_cols <- c(
  "spring.mean.temp",
  "prev_spring.mean.temp",
  "summer.tot.precip",
  "winter.mean.min.temp",
  "prev_winter.tot.precip"
)

base_row <- params[1, ]

base_row[] <- NA
base_row$Year <- "base"
base_row$scenario <- "base"
base_row[climate_cols] <- 0

params <- bind_rows(base_row, params)

#for any years without data, make 0 (average RE)
params <- params %>%
  mutate(across(
      c(growth_re, pflower_re, no.flow_re,
        surv_re),
      ~ tidyr::replace_na(., 0)))

params <- params %>% 
  filter(Year!="2026")

params <- params %>%
  left_join(pest, by = "Year") |> 
  mutate(pest = ifelse(is.na(pest), mean_est, pest))
```

```{r}
### 1. GROWTH
#gm.su.sp <- lmer(log.no.stemsT1 ~ log.no.stems + spring.mean.temp + summer.tot.precip + (1|Plot) + (1|Year), data = dac, REML = F)
growth <- fixef(gm.su.sp)
#growth intercept
params$growth.int <- growth["(Intercept)"] + growth["summer.tot.precip"] * params$summer.tot.precip + growth["spring.mean.temp"] * params$spring.mean.temp + params$growth_re
#growth slope
params$growth.slope <- growth["log.no.stems"]

growth_var <- as.data.frame(VarCorr(gm.su.sp)) #assumes same variance across all
params$growth.sd <- growth_var[growth_var$grp=="Residual","sdcor"] # growth sd of residuals

### 2. pflower
#fm.prev_spring.mean.temp <- glmer(pflowerT ~ log.no.stems + prev_spring.mean.temp + (1|Plot) + (1|Year), data = dac, family = "binomial")
flowering <- fixef(fm.prev_spring.mean.temp)
#intercept
params$pflow.int<- flowering["(Intercept)"] + flowering["prev_spring.mean.temp"] * params$prev_spring.mean.temp + params$pflower_re
#slope:
params$pflow.slope <- flowering["log.no.stems"]

####################### 3. no.flowers
#poisson.sp.wt.int2 <- glmer(No.panicles ~ log.no.stems*prev_winter.tot.precip + prev_spring.mean.temp+ (1|Plot) + (1|Year), data = subset(dac, pflowerT == "1"), family = "poisson")

panicles <- fixef(poisson.sp.wt.int2)

params$no.flow.int <- panicles["(Intercept)"] +
  panicles["prev_spring.mean.temp"] * params$prev_spring.mean.temp +
  panicles["prev_winter.tot.precip"] * params$prev_winter.tot.precip + params$no.flow_re

params$no.flow.slope <- panicles["log.no.stems"] +
  panicles["log.no.stems:prev_winter.tot.precip"] * params$prev_winter.tot.precip

### 4. sm.wt.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + winter.mean.min.temp + (1|Plot) + (1|Year), data = dac.surv, family = "binomial")

#sm.wt.sp.int <- glmer(survT1 ~ log.no.stems*prev_spring.mean.temp + winter.mean.min.temp + (1|Plot) + (1|Year), data = dac.survival, family = "binomial")
survival <- fixef(sm.wt.sp.int)

params$surv.int <- survival["(Intercept)"] +
  survival["prev_spring.mean.temp"] * params$prev_spring.mean.temp +
  survival["winter.mean.min.temp"] * params$winter.mean.min.temp + params$surv_re

params$surv.slope <- survival["log.no.stems"] +
  survival["log.no.stems:prev_spring.mean.temp"] * params$prev_spring.mean.temp


#params$no.seeds <- no.seeds
# params$pest <- pest


params$recruit.size.mean <- new_mean # mean new 
params$recruit.size.sd<- new_sd # sd of new 


```

```{r}
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
###         Load functions
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#SURVIVAL AT SIZE X
s.x=function(x,params) {
	u=exp(params$surv.int+params$surv.slope*x)
	return(u/(1+u))
}

#how to test this: 
### run function for a plant of size 1 and for the first row of parameters
#s.x(x = 1, params = params[1,])
### run function for a plant of size 1 but for all rows of parameters (so get a list )
#s.x(x = 1, params = params)
#ok this works and seems to work for all rows of params. great.

#GROWTH FROM SIZE X TO Y; 
  ## returns a *probability density distribution* for each x value
g.yx<-function(y,x,params){
    # eviction here...
  xb=pmin(pmax(x,minRealsize),maxRealsize) #Transforms all values below/above limits in min/max size (floor & ceiling)
  growth_to_newsize <-params$growth.int + params$growth.slope*xb
  growth_sd <- params$growth.sd
  return(dnorm(y,mean=growth_to_newsize,sd=growth_sd))
  #dnorm(y,mean=params$growth.int + params$growth.slope*x,sd=params$growth.sd)
}

#Tom Miller's combined s and g kernel
P <- function(y, x, params){
  s.x(x, params)*g.yx(y, x, params)
}

#PROBABILITY OF FLOWERING OF SIZE X individuals
pf.x <-function(x,params){
	u<-exp(params$pflow.int+params$pflow.slope*x)
	return(u/(1+u))
}
#testing this for a plant of size 5
#pf.x(x = 8,params = params_expanded)

f.yx <- function(x,params) { 		
  return(pf.x(x,params)*exp(params$no.flow.int+params$no.flow.slope*x)* params$pest)
}
##so this should be outputting the number of new plants made? Yes. pflower * how many flowers made * p(panicle making seedling)
#f.yx(x = 7,params = params_original)


##do big plants make a million flowers?
#exp(params$no.flow.int+params$no.flow.slope*8) 
## no they make a reasonable amount

#SIZE DISTRIBUTION OF RECRUITS - so the ones going from the continuous into the continuous stage. 
recruit.size<-function(y,params){
    ## returns a *probability density distribution*
  dnorm(y,mean=params$recruit.size.mean,sd=params$recruit.size.sd)
}
```

```{r}
params <- params %>%
  mutate(kernel_id = row_number())

params_list <- params %>%
  split(.$kernel_id)
#params_list <-  filter(params) %>% split(., seq(nrow(.))) #this splits up params into X rows, which I can feed into the function below

###
mat.size = 100 #dimensions of continuous matrix
bigmatrix <- function(params_list, mat.size){

  n <- mat.size
  L <- min.size
  U <- max.size

  # mesh
  h <- (U - L) / n
  b <- L + c(0:n) * h
  y <- 0.5 * (b[1:n] + b[2:(n+1)])

  # Fertility matrix
  Fmat <- matrix(0, n, n)

  # recruits of size y from parent size x
  Fmat <- outer(y, y, function(y,x){
    f.yx(x, params_list) * recruit.size(y, params_list)
  }) * h

  # Growth/survival
  Tmat <- t(outer(y, y, P, params = params_list)) * h

  # Full kernel
  IPMmat <- Fmat + Tmat

  out_matrix <- list(
    IPMmat = IPMmat,
    Fmat = Fmat,
    Tmat = Tmat,
    meshpts = y)

  out_lamb <- data.frame(
    Year = params_list$Year,
    scenario = params_list$scenario,
    lambda = lambda(IPMmat),
    prev_spring.mean.temp = params_list$prev_spring.mean.temp,
    winter.mean.min.temp = params_list$winter.mean.min.temp,
    summer.tot.precip = params_list$summer.tot.precip,
    spring.mean.temp = params_list$spring.mean.temp,
    prev_winter.tot.precip= params_list$prev_winter.tot.precip,
    kernel_id = params_list$kernel_id)

return(list(
  IPMmat = IPMmat,
  Fmat = Fmat,
  Tmat = Tmat,
  meshpts = y,
  lambda = out_lamb))
}

#what I want returned is lambdas
#lamb_lists <- lapply(X = params_list, FUN = bigmatrix, mat.size = mat.size) #for each row of params_list, run the big matrix function!

#great~! now make it a df
results <- lapply(params_list, bigmatrix, mat.size = mat.size)

dac_lambda <- do.call(rbind, lapply(results, function(x) x$lambda)) #run this one to get df of lambdas

kernels <- lapply(results, function(x) x$IPMmat)
kernel_info <- params %>%
  select(Year)
```



```{r yearly lambda figure}

(yearly <- dac_lambda %>%
   filter(scenario == "current") |> 
  ggplot(aes(x = Year, y = lambda, group = 1)) +
  geom_line(size = 1.2) +
  geom_point(size = 1.2) +
  geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(
    x = "year",
    y = expression(lambda)) )


(wt.p <- dac_lambda %>%
   filter(scenario == "current") |> 
    ggplot( aes(x = prev_winter.tot.precip, y = lambda)) +
  geom_point(size = 2) +
  geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(
    x = "Previous winter precipitation",
    y = expression(lambda),
    color = "Year" ))
(sm.p <- dac_lambda %>%
   filter(scenario == "current") |> 
    ggplot(aes(x = summer.tot.precip, y = lambda)) +
  geom_point(size = 2) +
  geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(x = "Summer precipitation",
    y = expression(lambda),
    color = "Year"))

(wt.t<- dac_lambda %>%
   filter(scenario == "current") |> 
    ggplot(aes(x = winter.mean.min.temp, y = lambda)) +
  geom_point(size = 2) +
    geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(
    x = "Winter min temperature",
    y = expression(lambda),
    color = "Year" ))
(prev.sp <- dac_lambda %>%
   filter(scenario == "current") |> 
    ggplot(aes(x = prev_spring.mean.temp, y = lambda)) +
  geom_point(size = 2) +
      geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(x = "Previous spring mean temperature",
    y = expression(lambda),
    color = "Year"))
(sp <- dac_lambda %>%
   filter(scenario == "current") |> 
    ggplot(aes(x = spring.mean.temp, y = lambda)) +
  geom_point(size = 2) +
  geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(x = "Spring mean temperature",
    y = expression(lambda),
    color = "Year"))
# (sp.temp <- dac_lambda %>%
#   filter(summer.tot.precip == 0, summer.mean.max.temp == 0) %>% 
#   ggplot(aes(x = spring.temp, y = lambda, color = trt)) +
#   geom_line(size = 1.2) +
#   scale_y_continuous(limits = y_limits) +
#   scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3"))+
#   labs(
#     x = "Spring Temperature",
#     y = expression(lambda),
#     color = ""
#   ) )
 (together <- (wt.p + wt.t)/ (prev.sp + sp) / (sm.p +  plot_spacer())+  plot_layout(guides = "collect"))

(yearly <- dac_lambda %>%
  ggplot(aes(x = Year, y = lambda, group = 1)) +
  geom_line(size = 1.2) +
  geom_point(size = 1.2) +
  facet_wrap(~scenario)+
  labs(
    x = "year",
    y = expression(lambda)) +
    theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
))

ggsave(here("Figures", "Dactylis", "dac.yearly.pop.growth.png"), plot = yearly, width = 7.5, height =5)
ggsave(here("Figures", "Dactylis", "yearly.pop.growth.by.climate.png"), plot = together, width = 12, height =8)

```

Get the SSD to start the stohcastic simulation at:
```{r}
# Base kernel (single kernel)
base_kernel <- kernels[[which(dac_lambda$scenario == "base")]]
#
get_ssd <- function(base_kernel, N0, years) {
  
  # initial population distribution
  n <- rep(N0 / nrow(base_kernel), nrow(base_kernel))
  
  # project population for specified number of years
  for(i in 1:years) {
    
    n <- base_kernel %*% n
    
    # keep abundance constant, retain size distribution
    n <- n / sum(n) * N0
  }
  
  # stable size distribution
  ssd <- n / sum(n)
  
  return(ssd)
}

# simulate 100 years to get SSD
ssd <- get_ssd(base_kernel, N0 = 1000, years = 100) #this will be used for all of the simualtions
```


```{r stochastic ipm where climate is the  warmer/precip changes}
scenario_names <- setdiff(unique(dac_lambda$scenario), "base")

scenario_kernels <- lapply(scenario_names, function(sc) {
  kernels[dac_lambda$scenario == sc]
})
names(scenario_kernels) <- scenario_names

stochastic_ipm <- function(scenario_kernels, ssd, N0, years, reps) {
  
  lambda_summary <- list()
  
  for(sc in names(scenario_kernels)) {
    
    kernel_list <- scenario_kernels[[sc]]
    
    # store one stochastic lambda per replicate
    rep_lambda <- numeric(reps)
    
    for(r in 1:reps) {
      
      # start from stable size distribution
      n <- ssd * N0
      
      annual_lambda <- numeric(years)
      
      for(t in 1:years) {
        
        N_before <- sum(n)
        
        # sample kernel only within this scenario
        K <- kernel_list[[sample(seq_along(kernel_list), 1)]]
        
        # project population
        n <- K %*% n
        
        N_after <- sum(n)
        
        # annual growth rate
        annual_lambda[t] <- N_after / N_before
      }
      
      # stochastic lambda for this replicate
      rep_lambda[r] <- exp(mean(log(annual_lambda)))
    }
    
    # mean stochastic lambda across replicates
    lambda_s <- exp(mean(log(rep_lambda)))
    
    # confidence interval among replicate stochastic lambdas
    lambda_CI <- quantile(rep_lambda, c(0.025, 0.975))
    
    lambda_summary[[sc]] <- data.frame(
      scenario = sc,
      stochastic_lambda = lambda_s,
      lower_CI = lambda_CI[1],
      upper_CI = lambda_CI[2]
    )
  }
  
  return(do.call(rbind, lambda_summary))
}

stoch_lambda <- stochastic_ipm(
  scenario_kernels = scenario_kernels,
  ssd = ssd,
  N0 = 1000,
  years = 100,
  reps = 10000
)

write.csv(stoch_lambda, here("clean_data", "stoch_ipm", "dactylis.stoch.lambda.csv"), row.names = FALSE)

```


```{r}
(
lam.s <- stoch_lambda |> 
  filter(scenario != "future") |> 
  ggplot(
       aes(x = scenario, y = stochastic_lambda)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymin = lower_CI, ymax = upper_CI),
                width = 0.15,
                linewidth = 1) +
  geom_hline(yintercept = 1, 
             linetype = "dashed", 
             color = "grey") +
  scale_x_discrete(
    labels = c(
      "current" = "Current",
      "future.precip" = "Precip change",
      "future.temp" = "Temp change",
      "future" = "Future"
    )
  ) +
  labs(
    x = "",
    y = "Stochastic lambda (λs)",
    title = "Dactylis"
  ))

ggsave(here("Figures", "Dactylis", "STOCH_LAM_SCENARIOS.png"), plot = lam.s, width = 6, height =5)

```



Not fixing the rest for now...
```{r}
#just make bad years more common - say, 3 years where climate is warmest/driest
#filter out the current scenarios
current_idx <- params$kernel_id[params$scenario == "current"]

kernels_current <- kernels[current_idx]

kernel_info_current <- params %>%
  filter(scenario == "current") %>%
  select(kernel_id, Year, scenario, summer.tot.precip)
identical(
  names(kernels_current),
  as.character(kernel_info_current$kernel_id)
)

dry_years <- kernel_info_current %>%
  arrange(summer.tot.precip) %>%
  slice(1:3) %>%
  pull(Year)

drought_options <- c(
  normal = 1,
  drought_1.5x = 1.5,
  drought_2x = 2,
  drought_3x = 3
)

weight_list <- lapply(drought_options, function(mult) {
  
  ifelse(
    kernel_info_current$Year %in% dry_years,
    mult,
    1
  )
})

names(weight_list) <- names(drought_options)

stochastic_ipm <- function(kernels, kernel_info, ssd, N0, years, reps) {
  
  rep_lambda <- numeric(reps)
  
  for(r in 1:reps) {
    
    n <- ssd * N0
    annual_lambda <- numeric(years)
    
    for(t in 1:years) {
      
      N_before <- sum(n)
      
      K <- kernels[[sample(
        seq_along(kernels),
        1,
        prob = kernel_info$weight
      )]]
      
      n <- K %*% n
      
      N_after <- sum(n)
      annual_lambda[t] <- N_after / N_before
    }
    
    rep_lambda[r] <- exp(mean(log(annual_lambda)))
  }
  
  data.frame(
    stochastic_lambda = exp(mean(log(rep_lambda))),
    lower_CI = quantile(rep_lambda, 0.025),
    upper_CI = quantile(rep_lambda, 0.975)
  )
}

# stoch_lambda_freq <- stochastic_ipm(
#   kernels = kernels_current,
#   kernel_info = kernel_info_current %>%
#     mutate(weight = weight_list$normal),
#   ssd = ssd,
#   N0 = 1000,
#   years = 100,
#   reps = 10000
# )

stoch_lambda_freq <- lapply(names(weight_list), function(scn) {
  
  stochastic_ipm(
    kernels = kernels_current,
    kernel_info = kernel_info_current %>%
      mutate(weight = weight_list[[scn]]),
    ssd = ssd,
    N0 = 1000,
    years = 100,
    reps = 10000
  ) %>%
    mutate(drought_scenario = scn)
  
}) %>%
  bind_rows()

stoch_lambda_freq |> 
  mutate(
    drought_scenario = factor(
      drought_scenario,
      levels = c("normal", "drought_1.5x", "drought_2x", "drought_3x")
    )
  ) |> 
ggplot(
       aes(x = drought_scenario, 
           y = stochastic_lambda)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = lower_CI, ymax = upper_CI), width = 0.1) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  theme_minimal() +
  labs(x = "",
       y = expression(stochastic~lambda))
```

```{r}
kernel_info_current <- params %>%
  filter(scenario == "current") %>%
  select(
    kernel_id,
    Year,
    scenario,
    summer.tot.precip,
    spring.mean.temp,
    prev_spring.mean.temp,
    winter.mean.min.temp,
    prev_winter.tot.precip
  )

run_climate_frequency <- function(kernels,
                                  kernel_info,
                                  climate_var,
                                  extreme = "high",
                                  multipliers = c(1, 1.5, 2, 3),
                                  ssd,
                                  N0 = 1000,
                                  years = 100,
                                  reps = 10000) {
  
  # identify extreme years
  if(extreme == "high") {
    extreme_years <- kernel_info %>%
      arrange(desc(.data[[climate_var]])) %>%
      slice(1:3) %>%
      pull(Year)
  } else {
    extreme_years <- kernel_info %>%
      arrange(.data[[climate_var]]) %>%
      slice(1:3) %>%
      pull(Year)
  }
  
  # scenario names
  scenario_names <- c(
    "normal",
    "1.5x",
    "2x",
    "3x"
  )
  
  # run each frequency scenario
  results <- lapply(seq_along(multipliers), function(i) {
    
    weights <- ifelse(
      kernel_info$Year %in% extreme_years,
      multipliers[i],
      1
    )
    
    stochastic_ipm(
      kernels = kernels,
      kernel_info = kernel_info %>%
        mutate(weight = weights),
      ssd = ssd,
      N0 = N0,
      years = years,
      reps = reps
    ) %>%
      mutate(
        climate_variable = climate_var,
        scenario = scenario_names[i]
      )
  })
  
  bind_rows(results)
}

climate_scenarios <- tibble(
  climate_var = c(
    "summer.tot.precip",
    "spring.mean.temp",
    "prev_spring.mean.temp",
    "winter.mean.min.temp",
    "prev_winter.tot.precip"
  ),
  extreme = c(
    "low",   # driest summers
    "high",  # warmest springs
    "high",  # warmest previous springs
    "high",  # warmest winters
    "high"   # wettest winters
  )
)

climate_frequency_results <- purrr::pmap_dfr(
  climate_scenarios,
  function(climate_var, extreme) {
    
    run_climate_frequency(
      kernels = kernels_current,
      kernel_info = kernel_info_current,
      climate_var = climate_var,
      extreme = extreme,
      ssd = ssd,
      N0 = 1000,
      years = 100,
      reps = 10000
    )
    
  }
)

(freq.year <- climate_frequency_results %>%
  filter(!(scenario == "normal" & climate_variable != "summer.tot.precip")) %>%
  mutate(
    climate_variable = ifelse(
      scenario == "normal",
      "base",
      climate_variable
    ),
    scenario = factor(
      scenario,
      levels = c("base", "1.5x", "2x", "3x")
    )
  ) |> 
 ggplot(
       aes(x = climate_variable,
           y = stochastic_lambda,
           color = scenario,
           group = scenario)) +
  geom_point(size = 3,    position = position_dodge(width = 0.4)) +
  geom_errorbar(
    aes(ymin = lower_CI, ymax = upper_CI),
    width = 0.1, position = position_dodge(width = 0.4)
  ) +
    theme_minimal() +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  ) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(
    x = "",
    y = expression(stochastic~lambda),
    color = "Extreme year frequency"
  ))
ggsave(here("Figures", "Dactylis", "STOCH_LAM_YR_FREQ.png"), plot = freq.year, width = 6, height =5)

```

Ok the last thing to try before ESA:
Just perturn temp and precip separately, and what's in line with the climate projections
```{r}

```

