---
title: "lomatium.vital.rates"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(here)
library(tidyverse)
library(lme4)
library(AICcmodavg)
library(patchwork)
library(gt) #for saving tables in a word doc
theme_set(theme_classic(base_size = 18)) #for ggplot

```

```{r}
lom <- read.csv(here("clean_data", "Lomatium_Demography_Data_CLEANED_2016thru2026.csv"))
climate <- read.csv(here("clean_data", "CGOP_climatevalues_scaled.csv"))
climate<- climate %>%
  arrange(year) %>%
  mutate(across(-year, ~lag(.x), .names = "prev_{.col}"))#%>% 
  #select(c(year, winter.mean.min.temp, prev_winter.mean.min.temp, summer.mean.max.temp, prev_summer.mean.max.temp, spring.mean.temp, prev_spring.mean.temp, fall.mean.temp, prev_fall.mean.temp, ends_with("tot.precip")))

#scott used size.t = log(No.leaves.t * Leaf.length.t) as the size measurement
lom <- left_join(lom, climate, by = c("Year" = "year"))
lom <- lom %>% 
  group_by(plantid) %>% 
  mutate(Year = as.factor(Year), 
         Plot = as.factor(Plot),
          psurvival = factor(psurvival, levels = c(0, 1)),
          psurvivalT1 = as.character(psurvivalT1),
         psurvivalT1 = factor(psurvivalT1, levels = c(0, 1)),
         pflower = factor(pflower, levels = c(0, 1)),
         pflowerT1 = factor(pflowerT1, levels = c(0, 1)),
         pseeds = factor(pseeds, levels = c(0, 1)),
    size = if_else(No.leaves > 0& Leaf.length>0, log(No.leaves* Leaf.length), NA),
         sizeT1 = lead(size),
    trt = as.factor(trt),
    trt = fct_relevel(trt, "irrigated", "control", "drought")) %>% 
  filter(Plot != "11",
         Year != "2016") #no. leaves were miscounted

lom.surv <- lom %>% 
  filter(!Year %in% c("2025", "2026"),
  !is.na(psurvivalT1))

seeds <- lom %>% 
  filter(!is.na(no.seeds))
```

```{r}
#get pop sizes year to year and lambda
lam <- lom %>%
  filter(Xcoor < 10) %>%
  mutate(Year = as.numeric(as.character(Year))) %>%  # fix ordering
  group_by(Year, Plot) %>%
  summarise(
    n = sum(psurvival == 1, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Plot, Year) %>%
  group_by(Plot) %>%
  mutate(
    lambda = lead(n) / n
  ) %>%
  ungroup()

lam.all <- lom %>%
  mutate(Year = as.numeric(as.character(Year))) %>%
  group_by(Year) %>%
  summarise(
    n = sum(psurvival == 1, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Year) %>%
  mutate(
    lambda = lead(n) / n
  )
(lambda <- ggplot(lam, aes(x = as.character(Year), y = lambda, color = Plot)) +
  geom_line(aes(group = Plot), alpha = 0.5) +
  geom_point() +
  geom_hline(yintercept = 1)+
  labs(x = "Year", y = expression(lambda)) +
  theme_minimal())
(n <- ggplot(lam, aes(x = as.character(Year), y = n, color = Plot)) +
  geom_line(aes(group = Plot), alpha = 0.5) +
  geom_point() +
  labs(x = "Year", y = "Number of plants") +
  theme_minimal())
(to <- lambda/n +plot_layout(guides = "collect")
)

(n.size <- 
  lam.all %>%
  group_by(Year) %>%
  summarise(n = sum(n, na.rm = TRUE), .groups = "drop") %>%
  ggplot(aes(x = Year, y = n, group = 1)) +
  geom_line(alpha = 0.5) +
  geom_point() +
  labs(x = "Year", y = "Number of plants") +
  theme_minimal())

(lambda.size <- ggplot(lam.all, aes(x = as.character(Year), y = lambda, group = 1)) +
  geom_line(alpha = 0.5) +
  geom_point() +
  geom_hline(yintercept = 1)+
  labs(x = "Year", y = expression(lambda)) +
  theme_minimal())

(to.size
  <- lambda.size/n.size +plot_layout(guides = "collect")
)
ggsave(here("Figures", "Lomatium", "groundtruth.lambda.png"), plot = to, width = 8, height =6)
ggsave(here("Figures", "Lomatium", "groundtruth.lambda.plots pooled.png"), plot = to.size, width = 8, height =6)

```


```{r Sample Plots}
#sample plots
lom %>% ggplot(aes(x = size, y = sizeT1, color = trt))+
  geom_point()+
  geom_abline(slope=1, intercept = 0, color= "black", linewidth = .2)
lom %>% ggplot(aes(x = size, y = sizeT1, color = trt))+
  geom_point()+
  geom_smooth(method = "lm", se = F)+
  facet_wrap(~Year)+
  geom_abline(slope=1, intercept = 0, color= "black", linewidth = .2)
lom %>% ggplot(aes(x = size, y = sizeT1, color = trt))+
  geom_point()+
  geom_smooth(method = "lm", se = F)+
  facet_wrap(~Plot)+
  geom_abline(slope=1, intercept = 0, color= "black", linewidth = .2)
#plot 11 probably needs to be excluded
#survival
lom %>% filter(!is.na(psurvivalT1)) %>% 
  ggplot(aes(x = size, y = as.numeric(psurvivalT1)-1, color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="binomial"), se = F)
lom %>% filter(!is.na(psurvivalT1)) %>% 
  ggplot(aes(x = size, y = as.numeric(psurvivalT1)-1, color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="binomial"), se = F)+
  facet_wrap(~Year)
lom %>% filter(!is.na(psurvivalT1)) %>% 
  ggplot(aes(x = size,  y = as.numeric(psurvivalT1)-1, color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="binomial"), se = F)+
  facet_wrap(~Plot)

#flowering
lom %>% filter(!is.na(pflowerT1)) %>% 
  ggplot(aes(x = size, y = as.numeric(pflowerT1)-1, color = trt))+
  geom_jitter()+
  geom_smooth(method="glm",
    method.args=list(family="binomial"), se = F)
lom %>% filter(!is.na(pflowerT)) %>% 
  ggplot(aes(x = size, y = as.numeric(pflowerT1), color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="binomial"), se = F)+
  facet_wrap(~Year)
lom %>% filter(!is.na(pflowerT1)) %>% 
  ggplot(aes(x = size,  y = as.numeric(pflowerT1), color = trt))+
  geom_jitter()+
  geom_smooth(method="glm",
    method.args=list(family="binomial"), se = F)+
  facet_wrap(~Plot)

#no.umbels
lom %>% filter(pflowerT == 1) %>% 
  ggplot(aes(x = size, y = No.panicles, color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="poisson"), se = F)
lom %>% filter(pflowerT == 1) %>% 
  ggplot(aes(x = size, y = No.panicles, color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="poisson"), se = F)+
  facet_wrap(~Year)
lom %>% filter(pflowerT == 1) %>% 
  ggplot(aes(x = size,  y = No.panicles, color = trt))+
  geom_point()+
  geom_smooth(method="glm",
    method.args=list(family="poisson"), se = F)+
  facet_wrap(~Plot)
```
fine for now but need to go through and deal with Scott's code!
```{r}
#size in current year or past year for flowering
lom_complete <- lom[complete.cases(lom[, c("pflower", "pflowerT1", "size", "Year", "Plot")]), ]
f.test1  <- glmer(pflower ~ size+ (1|Year) + (1|Plot) , data = lom_complete, family = "binomial")
f.test2  <- glmer(pflowerT1 ~ size+ (1|Year) + (1|Plot) , data = lom_complete, family = "binomial")
AIC(f.test1, f.test2) #one is better

```


```{r growth prequel}
base <- lmer(sizeT1 ~ size*Year + (1|Plot), data = lom, REML = F)
drop1(base,test="Chisq")
# base2 <- lmer(log.no.stemsT1 ~ log.no.stems+Year + (1|Plot), data = lom, REML = F)
# base3 <- lmer(log.no.stemsT1 ~ log.no.stems+ (1|Plot), data = lom, REML = F)
# a2 <- anova(base3, base2, test="LRT") #yes year is significant
best.growth <- lmer(sizeT1 ~ size + (1|Year) + (1|Plot), data = lom, REML = F)

re_year <- rownames_to_column(
  as.data.frame(ranef(best.growth)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year))%>% 
  rename(int = `(Intercept)`)

# 
grow.corr <- left_join(re_year, climate) %>% 
  select(-year)

# Compute correlations and p-values
cor_results <- lapply(names(grow.corr), function(v) {
  test <- cor.test(grow.corr$int, grow.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_growth <- do.call(rbind, cor_results)

# Sort by absolute correlation
cor_results_growth <- cor_results_growth[order(-abs(cor_results_growth$correlation)), ]
#prev_spring.tot.precip

###
#these are the ones to test
vars <- c("summer.mean.min.temp", "prev_spring.mean.min.temp")

# Unique climate-year values
lom.unique <- lom %>%
  ungroup() |> 
  distinct(Year, across(all_of(vars)))

# All pairwise combinations
pairs <- combn(vars, 2, simplify = FALSE)

cor_results <- map_dfr(pairs, function(p) {
  x <- lom.unique[[p[1]]]
  y <- lom.unique[[p[2]]]
  ct <- cor.test(x, y)
  tibble(
    var1 = p[1],
    var2 = p[2],
    estimate = unname(ct$estimate),
    statistic = unname(ct$statistic),
    p.value = ct$p.value,
    conf.low = ct$conf.int[1],
    conf.high = ct$conf.int[2]
  )
})

cor_results
pairs <- combn(vars, 2, simplify = FALSE)

pairs
#dont test these together...correlated!

```


```{r growth model selection}
gm.base.size <- lmer(sizeT1 ~ size + (1|Plot) + (1|Year), data = lom, REML = F)
gm.base.trt <- lmer(sizeT1 ~ size+ trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.base.trt.int <- lmer(sizeT1 ~ size*trt + (1|Plot) + (1|Year), data = lom, REML = F)

# ##grow season total precip

gm.ps.temp <- lmer(sizeT1 ~ size  + prev_spring.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.q <- lmer(sizeT1 ~ size  + prev_spring.mean.min.temp + I(prev_spring.mean.min.temp^2) + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.int <- lmer(sizeT1 ~ size *prev_spring.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.trt <- lmer(sizeT1 ~ size  + prev_spring.mean.min.temp + trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.trt.int1 <- lmer(sizeT1 ~ size *prev_spring.mean.min.temp + trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.trt.int2 <- lmer(sizeT1 ~ size  + prev_spring.mean.min.temp*trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.trt.int3 <- lmer(sizeT1 ~ size*trt + prev_spring.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
gm.ps.temp.trt.int4 <- lmer(sizeT1 ~ size*trt + trt*prev_spring.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)

# #summer.mean.min.temp
gm.s.min.temp <- lmer(sizeT1 ~ size + summer.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.q <- lmer(sizeT1 ~ size + summer.mean.min.temp + I(summer.mean.min.temp^2) + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.int <- lmer(sizeT1 ~ size*summer.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.trt <- lmer(sizeT1 ~ size + summer.mean.min.temp + trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.trt.int1 <- lmer(sizeT1 ~ size*summer.mean.min.temp + trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.trt.int2 <- lmer(sizeT1 ~ size + summer.mean.min.temp*trt + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.trt.int3 <- lmer(sizeT1 ~ size*trt + summer.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
gm.s.min.temp.trt.int4 <- lmer(sizeT1 ~ size*trt + trt*summer.mean.min.temp + (1|Plot) + (1|Year), data = lom, REML = F)
################################################################################
###
growth <- mget(ls(pattern = "^gm")) #make a list of all of those models that start with gm (^ means start with)
growth_AICc<-aictab(cand.set = growth, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("gm", ls())]) #removes everything with gm


summary(gm.s.min.temp.trt.int4)
```

```{r save growth}
growth_AICc2 <- growth_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(growth, get_fixed_formula)

growth_AICc2$fixed_effects <- fixed_formulas[growth_AICc2$Modnames]


growth.d <- growth_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

growth.d %>% gt() %>% gtsave(here("Tables", "Lomatium", "Lomatium.AIC.table.growth.docx"))

#save the best fit model
summary(gm.s.min.temp.trt.int4)
coefs <- summary(gm.s.min.temp.trt.int4)$coefficients

g.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(g.coef, here("Tables", "Lomatium", "lomatium_growth_best_fit_coeff.csv"), row.names = F)
```

```{r growth figure}
summary(gm.s.min.temp.trt.int2)
pred.dat.g <- expand.grid(size = seq(min(lom$size, na.rm = TRUE), max(lom$size, na.rm = TRUE), by = .1),  trt = c("irrigated", "control", "drought"), summer.mean.min.temp = c(-1, 1))
pred.dat.output.g <- cbind(pred.dat.g, as.data.frame(predict(gm.s.min.temp.trt.int4
, newdata = pred.dat.g, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.g)[ncol(pred.dat.output.g)] <- "sizeT1"  # Renaming the last column


(growth.fig <- lom %>%
  ggplot(aes(x = size, y = sizeT1)) +
  geom_point(data = lom, alpha = 0.4, shape = 1) +
  geom_line(data = pred.dat.output.g,
            aes(color = factor(summer.mean.min.temp)), linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1),
        legend.position = c(0.1, 0.85),
        legend.background = element_rect(fill = NA, colour = NA),
                legend.title = element_text(size = 9),
        legend.text = element_text(size = 8),
        legend.key = element_rect(fill = NA, colour = NA),
                legend.key.size = unit(0.4, "cm")) +
  geom_abline(slope = 1, intercept = 0, color = "grey", linewidth = .4) +
  scale_color_manual(values = c("#8cbaec", "#f77550"), labels = c("Cool", "Warm")) +
  scale_y_continuous(expand = c(0, 0), limits = c(-.25, 6)) +
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 6)) +
  facet_wrap(~trt) +
  labs(x = "log(Size) in t", y = "log(Size) in t + 1", color = "Summer min temp, t"))

ggsave(here("Figures", "Lomatium", "growth.png"), plot = growth.fig, width = 8, height =4)


```

```{r pflower prequel}
table(lom$pflower, lom$Year)
base.p <- glmer(pflower ~ size*Year + (1|Plot) , data = lom, family = "binomial", control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
drop1(base.p,test="Chisq") 
#keep interaction terms between size and climate
best.pflower <- glmer(pflower ~ size + (1|Year) + (1|Plot), data = lom, family = "binomial")


re_year <- rownames_to_column(
  as.data.frame(ranef(best.pflower)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year))%>% 
  rename(int = `(Intercept)`)

pflower.corr <- left_join(re_year, climate) %>% 
  select(-year)

# get correlations and p-values
cor_results <- lapply(names(pflower.corr), function(v) {
  test <- cor.test(pflower.corr$int, pflower.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_pflower <- do.call(rbind, cor_results)
cor_results_pflower$p_value <- format(cor_results_pflower$p_value, scientific = FALSE)

# # Sort by absolute correlation
# cor_results_pflower <- cor_results_pflower[order(-abs(cor_results_pflower$correlation)), ]
# #prev_summer.mean.max.temp
# ###
# #these are the ones to test
# vars <- c("prev_spring.mean.temp", "prev_winter.mean.max.temp",
#           "prev_winter.tot.precip", 
#           "spring.tot.precip")
# 
# # Unique climate-year values
# dac.unique <- dac %>%
#   distinct(Year, across(all_of(vars)))
# 
# # All pairwise combinations
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# cor_results <- map_dfr(pairs, function(p) {
#   x <- dac.unique[[p[1]]]
#   y <- dac.unique[[p[2]]]
#   ct <- cor.test(x, y)
#   tibble(
#     var1 = p[1],
#     var2 = p[2],
#     estimate = unname(ct$estimate),
#     statistic = unname(ct$statistic),
#     p.value = ct$p.value,
#     conf.low = ct$conf.int[1],
#     conf.high = ct$conf.int[2]
#   )
# })
# 
# cor_results
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# pairs
```

```{r pflower model selection}
fm.base.size <- glmer(pflower ~ size + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.base.trt <- glmer(pflower ~ size+ trt + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.base.trt.int <- glmer(pflower ~ size*trt + (1|Plot) + (1|Year), data = lom, family = "binomial")

##winter.mean.max.temp
fm.wt <- glmer(pflower ~ size  + winter.mean.max.temp + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.q <- glmer(pflower ~ size  + winter.mean.max.temp + I(winter.mean.max.temp^2)+ (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.int <- glmer(pflower ~ size *winter.mean.max.temp + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.trt <- glmer(pflower ~ size  + winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.trt.int1 <- glmer(pflower ~ size *winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.trt.int2 <- glmer(pflower ~ size + winter.mean.max.temp*trt + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.trt.int3 <- glmer(pflower ~ size*trt + winter.mean.max.temp + (1|Plot) + (1|Year), data = lom, family = "binomial")
fm.wt.trt.int4 <- glmer(pflower ~ size*trt + trt*winter.mean.max.temp + (1|Plot) + (1|Year), data = lom, family = "binomial")


################################################################################
###
pflower <- mget(ls(pattern = "^fm")) #make a list of all of those models that start with gm (^ means start with)
pflower_AICc<-aictab(cand.set = pflower, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("fm", ls())]) #removes everything with gm

summary(fm.wt.trt.int4)
```

```{r save pflower}
pflower_AICc2 <- pflower_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(pflower, get_fixed_formula)

pflower_AICc2$fixed_effects <- fixed_formulas[pflower_AICc2$Modnames]


flower.d <- pflower_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

flower.d %>% gt() %>% gtsave(here("Tables", "Lomatium", "Lomatium.AIC.table.pflower.docx"))

#save the best fit model
summary(fm.wt.trt.int4)
coefs <- summary(fm.wt.trt.int4)$coefficients

f.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(f.coef, here("Tables", "Lomatium", "lomatium_pflower_best_fit_coeff.csv"), row.names = F)
```

```{r pflower figure}

pred.dat.p <- expand.grid(size = seq(min(lom$size, na.rm = TRUE), max(lom$size, na.rm = TRUE), by = .1), winter.mean.max.temp = c(-1, 1), trt = c("irrigated", "control", "drought"))
pred.dat.output.p <- cbind(pred.dat.p, as.data.frame(predict(fm.wt.trt.int4, newdata = pred.dat.p, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.p)[ncol(pred.dat.output.p)] <- "pflower"  # Renaming the last column
# 
(flow.fig <- lom %>%
  ggplot(aes(x = size, y = as.numeric(pflower)-1))+
  geom_jitter(data = lom ,alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = pred.dat.output.p, aes(y = pflower, color = as.character(winter.mean.max.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = "bottom")+
    scale_color_manual(name = "Winter max temp, t", values = c("#90d4cc", "#bd3027"), labels = c("cool", "warm")) +
    facet_wrap(~trt)+
  labs(x = "log(Size) in t", y = "P(Flowering) in t"))

ggsave(here("Figures", "Lomatium", "pflower.png"), plot = flow.fig, width = 8, height =4)

```

```{r survival prequel}

table(lom.surv$psurvivalT1, lom.surv$Year)
base.s <- glmer(psurvivalT1 ~ size*Year + (1|Plot) , data = lom.surv, family = "binomial", control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
drop1(base.s,test="Chisq") #yes, keep size*climate interactions

best.s <- glmer(psurvivalT1 ~ size + (1|Year) + (1|Plot) , data = lom.surv, family = "binomial")

re_year <- rownames_to_column(
  as.data.frame(ranef(best.s)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year))%>% 
  rename(int = `(Intercept)`)

surv.corr <- left_join(re_year, climate) %>% 
  select(-year)

# get correlations and p-values
cor_results <- lapply(names(surv.corr), function(v) {
  test <- cor.test(surv.corr$int, surv.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

cor_results_surv <- do.call(rbind, cor_results)

#fall.mean.temp only testing this one	
#prev_winter.mean.max.temp
#prev_winter.tot.precip	
#prev_spring.mean.max.temp	
#these are the ones to test
# vars <- c("fall.mean.temp", "prev_winter.mean.max.temp",
#           "prev_winter.tot.precip", "prev_spring.mean.max.temp")
# 
# # Unique climate-year values from dac.surv
# surv.unique <- lom.surv %>%
#   ungroup() |> 
#   distinct(Year, across(all_of(vars)))
# 
# # All pairwise combinations
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# cor_results <- map_dfr(pairs, function(p) {
#   x <- surv.unique[[p[1]]]
#   y <- surv.unique[[p[2]]]
#   ct <- cor.test(x, y)
#   tibble(
#     var1 = p[1],
#     var2 = p[2],
#     estimate = unname(ct$estimate),
#     statistic = unname(ct$statistic),
#     p.value = ct$p.value,
#     conf.low = ct$conf.int[1],
#     conf.high = ct$conf.int[2]
#   )
# })
# 
# cor_results
# 
# pairs <- combn(vars, 2, simplify = FALSE)
# 
# pairs
#only test: 
# [1] "fall.mean.temp"            "prev_winter.mean.max.temp"
# [1] "fall.mean.temp"         "prev_winter.tot.precip"
# [1] 
# [1] "prev_winter.mean.max.temp" "prev_spring.mean.max.temp"
```

```{r survival model selection}

sm.base.size <- glmer(psurvivalT1 ~ size + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.base.trt <- glmer(psurvivalT1 ~ size+ trt + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.base.trt.int <- glmer(psurvivalT1 ~ size*trt + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")

#fall.mean.temp
sm.f <- glmer(psurvivalT1 ~ size + fall.mean.temp + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.q <- glmer(psurvivalT1 ~ size + fall.mean.temp + I(prev_winter.mean.max.temp^2) + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.int <- glmer(psurvivalT1 ~ size*fall.mean.temp + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.trt <- glmer(psurvivalT1 ~ size + fall.mean.temp + trt + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.trt.int1 <- glmer(psurvivalT1 ~ size*fall.mean.temp + trt + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.int2 <- glmer(psurvivalT1 ~ size + fall.mean.temp*trt + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.int3 <- glmer(psurvivalT1 ~ size*trt + fall.mean.temp + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")
sm.f.int4 <- glmer(psurvivalT1 ~ size*trt + fall.mean.temp*trt + (1|Plot) + (1|Year), data = lom.surv, family = "binomial")

################################################################################
###
surv <- mget(ls(pattern = "^sm")) #make a list of all of those models that start with gm (^ means start with)
surv_AICc<-aictab(cand.set = surv, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)

#rm(list = ls()[grepl("sm", ls())]) #removes everything with gm



summary(sm.f.int2)
```
```{r save survival}
surv_AICc2 <- surv_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(surv, get_fixed_formula)

surv_AICc2$fixed_effects <- fixed_formulas[surv_AICc2$Modnames]


surv.d <- surv_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

surv.d %>% gt() %>% gtsave(here("Tables", "Lomatium", "Lomatium.AIC.table.survival.docx"))

#save the best fit model
summary(sm.f.int2)
coefs <- summary(sm.f.int2)$coefficients

s.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(s.coef, here("Tables", "Lomatium", "lomatium_survival_best_fit_coeff.csv"), row.names = F)
```

```{r survival figure}
pred.dat.s <- expand.grid(size = seq(min(lom$size, na.rm = TRUE), max(lom$size, na.rm = TRUE), by = .1), fall.mean.temp = c(-1, 1), trt = c("irrigated", "control", "drought"))
pred.dat.output.s <- cbind(pred.dat.s, as.data.frame(predict(sm.f.int2, newdata = pred.dat.s, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.s)[ncol(pred.dat.output.s)] <- "psurvivalT1"  # Renaming the last column


(s.sp <- lom.surv %>% 
  ggplot(aes(x = size, y = as.numeric(psurvivalT1)-1))+
  geom_jitter(alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = pred.dat.output.s, aes(y = psurvivalT1, color = factor(fall.mean.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = "bottom",   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+  
    scale_color_manual(name = "Fall temp, t", values = c("#71250E", "#EB781B"), labels = c("cool", "warm")) +
    facet_wrap(~trt)+
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 6))+
  labs(x = "log(Size) in t", y = "Survival in t + 1"))

ggsave(here("Figures", "Lomatium", "survival.png"), plot = s.sp, width = 8, height =4)

```

```{r pseeds prequel}
table(seeds$pflowerT, seeds$Year)
#table(seeds$no.seeds, seeds$Year)#6years of seed data
table(seeds$pseeds, seeds$Year)

probseeds.base.size <- glmer(pseeds ~ size + (1|Plot) + (1|Year), data = seeds, family = "binomial")

base.pseeds <- glmer(pseeds ~ size*Year + (1|Plot) , data = seeds, family = "binomial", control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
drop1(base.pseeds,test="Chisq") #keep size*climate interactions
# base.p2 <- glmer(pseeds ~ size+Year + (1|Plot) , data = seeds, family = "binomial")
# base.p3 <- glmer(pseeds ~ size+ (1|Plot), data = seeds, family = "binomial")
# a2 <- anova(base.p3, base.p2, test="LRT") #yes year is significant

re_year <- rownames_to_column(
  as.data.frame(ranef(pseeds.base.size)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year)) %>% 
    rename(int = `(Intercept)`)

probseeds.corr <- left_join(re_year, climate) %>% 
  select(-year)


# get correlations and p-values
cor_results <- lapply(names(pseeds.corr), function(v) {
  test <- cor.test(pseeds.corr$int, pseeds.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_pseeds <- do.call(rbind, cor_results)

# Sort by absolute correlation
cor_results_pseeds <- cor_results_pseeds[order(-abs(cor_results_pseeds$correlation)), ]

#ok so fall.tot.precip...that would be after they make the seeds. so ignore that
#spring.tot.precip


```

```{r pseeds model selection}
ps.base <- glmer(pseeds ~ size + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.base.trt <- glmer(pseeds ~ size+ trt + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.base.trt.int <- glmer(pseeds ~ size*trt + (1|Plot) + (1|Year), data = seeds, family = "binomial")

##spring.tot.precip
ps.s.precip <- glmer(pseeds ~ size  + spring.tot.precip + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.q <- glmer(pseeds ~ size  + spring.tot.precip + I(spring.tot.precip^2) + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.int <- glmer(pseeds ~ size*spring.tot.precip + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.trt <- glmer(pseeds ~ size  + spring.tot.precip + trt + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.trt.int2 <- glmer(pseeds ~ size  + spring.tot.precip*trt + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.trt.int3 <- glmer(pseeds ~ size*spring.tot.precip + trt + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.trt.int4 <- glmer(pseeds ~ size*trt  + spring.tot.precip + (1|Plot) + (1|Year), data = seeds, family = "binomial")
ps.s.precip.trt.int5 <- glmer(pseeds ~ size*trt  + trt*spring.tot.precip + (1|Plot) + (1|Year), data = seeds, family = "binomial")


probseeds <- mget(ls(pattern = "^ps.")) #make a list of all of those models that start with gm (^ means start with)
probseeds_AICc<-aictab(cand.set = probseeds, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)
#rm(list = ls()[grepl("ps.", ls())]) #removes everything with gm

summary(ps.s.precip)
```
```{r save pseeds}
probseeds_AICc2 <- probseeds_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(surv, get_fixed_formula)

probseeds_AICc2$fixed_effects <- fixed_formulas[probseeds_AICc2$Modnames]


aic.d <- probseeds_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

aic.d %>% gt() %>% gtsave(here("Tables", "Lomatium", "Lomatium.AIC.table.pseeds.docx"))

#save the best fit model
summary(ps.s.precip)
coefs <- summary(ps.s.precip)$coefficients

s.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(s.coef, here("Tables", "Lomatium", "lomatium_pseeds_best_fit_coeff.csv"), row.names = F)
```

```{r pseeds figure}
ps.s.precip <- glmer(pseeds ~ size  + spring.tot.precip + (1|Plot) + (1|Year), data = seeds, family = "binomial")

pred.dat.ps <- expand.grid(size = seq(min(seeds$size, na.rm = TRUE), max(seeds$size, na.rm = TRUE), by = .1), spring.tot.precip = c(-1, 1))
pred.dat.output.ps <- cbind(pred.dat.ps, as.data.frame(predict(ps.s.precip, newdata = pred.dat.ps, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.ps)[ncol(pred.dat.output.ps)] <- "pseeds"  # Renaming the last column

(pseeds.fig<- 
  seeds %>% 
  ggplot(aes(x = size, y = as.numeric(pseeds)-1))+
  geom_jitter(alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = pred.dat.output.ps, aes(y = pseeds, color = factor(spring.tot.precip)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.85, .25),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+  
  scale_color_manual(name = "Spring precip, t", values = c("#ea7f93", "#5b8957"), labels = c("dry", "wet")) +
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 5.25))+
  scale_x_continuous(expand = c(0, 0), limits = c(-.25, 6))+
  labs(x = "log(Size) in t", y = "P(plant making seeds) in t"))


ggsave(here("Figures", "Lomatium", "pseeds.png"), plot = pseeds.fig, width = 6, height =6)
```


```{r  noseeds prequel}
nseeds.base.size <- glmer.nb(no.seeds ~ size + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))

#base.pan <- glmer(no.seeds ~ size*Year + (1|Plot) , data = subset(seeds, no.seeds>0), family = "poisson")
#drop1(base.pan,test="Chisq") #yes, keep size*climate interactions
base.p2 <- glmer.nb(no.seeds ~ size + Year + (1|Plot) , data = subset(seeds, no.seeds>0))
base.p3 <- glmer.nb(no.seeds ~ size + (1|Plot) , data = subset(seeds, no.seeds>0))
a2 <- anova(base.p3, base.p2, test="LRT") #yes year is significant

re_year <- rownames_to_column(
  as.data.frame(ranef(nseeds.base.size)$Year),
  var = "year") %>% 
  mutate(year = as.numeric(year)) %>% 
  rename(int = `(Intercept)`)
  
pan.corr <- left_join(re_year, climate) %>% 
  select(-year)

# get correlations and p-values
cor_results <- lapply(names(pan.corr), function(v) {
  test <- cor.test(pan.corr$int, pan.corr[[v]])
  data.frame(
    variable = v,
    correlation = test$estimate,
    p_value = test$p.value
  )
})

# Combine into one data frame
cor_results_noseeds <- do.call(rbind, cor_results)
cor_results_noseeds$p_value <- format(cor_results_noseeds$p_value, scientific = FALSE)

#prev_summer.mean.min.temp
#winter.mean.max.temp
#prev_fall.mean.temp
cor.test(climate$prev_fall.mean.temp,
         climate$spring.mean.temp)

```


```{r panicles model selection}
#named these poisson but note they are negative binomials
poisson.base.size <-  glmer.nb(no.seeds ~ size + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.base.trt <- glmer.nb(no.seeds ~ size+ trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.base.trt.int <- glmer.nb(no.seeds ~ size*trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))

##grow season total precip
poisson.f <- glmer.nb(no.seeds ~ size  + prev_fall.mean.temp + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.f.trt <- glmer.nb(no.seeds ~ size  + prev_fall.mean.temp + trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.f.trt2 <- glmer.nb(no.seeds ~ size  + prev_fall.mean.temp*trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.f.trt3 <- glmer.nb(no.seeds ~ size*trt  + prev_fall.mean.temp + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
#poisson.f.trt4 <- glmer.nb(no.seeds ~ size*trt  + trt*prev_fall.mean.temp + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))


poisson.w <- glmer.nb(no.seeds ~ size  + winter.mean.max.temp + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.w.trt <- glmer.nb(no.seeds ~ size  + winter.mean.max.temp + trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.w.trt2 <- glmer.nb(no.seeds ~ size  + winter.mean.max.temp*trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.w.trt3 <- glmer.nb(no.seeds ~ size*trt + winter.mean.max.temp+ (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
#poisson.w.trt4 <- glmer.nb(no.seeds ~ size*trt + trt*winter.mean.max.temp+ (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))

poisson.s <- glmer.nb(no.seeds ~ size  + prev_summer.mean.min.temp + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.s.trt <- glmer.nb(no.seeds ~ size  + prev_summer.mean.min.temp + trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.s.trt2 <- glmer.nb(no.seeds ~ size  + prev_summer.mean.min.temp*trt + (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
poisson.s.trt3 <- glmer.nb(no.seeds ~ size*trt   + prev_summer.mean.min.temp+ (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))
#poisson.s.trt4 <- glmer.nb(no.seeds ~ size*trt   + trt*prev_summer.mean.min.temp+ (1|Plot) + (1|Year), data = subset(seeds, no.seeds>0))

################################################################################
###
umbels <- mget(ls(pattern = "^poisson")) #make a list of all of those models that start with gm (^ means start with)
panicles_AICc<-aictab(cand.set = umbels, modnames = NULL,second.ord=TRUE,nobs=NULL,sort=TRUE)
cor(seeds$spring.mean.temp, seeds$prev_fall.mean.temp)
#rm(list = ls()[grepl("poisson", ls())]) #removes everything with gm
summary(poisson.s.trt3)

```

```{r save no seeds}
panicles_AICc2 <- panicles_AICc |> 
  mutate(across(where(is.numeric), ~ round(.x, 3))) |> 
  arrange(AICc)

get_fixed_formula <- function(m) {
  f <- formula(m)
  rhs <- deparse(f[[3]], width.cutoff = 500)
  rhs <- paste(rhs, collapse = "")
  rhs <- gsub("\\s*\\+?\\s*\\(1\\s*\\|\\s*\\w+\\)", "", rhs)
  #rhs <- gsub("\\s*\\+?\\s*offset\\(log\\(total1\\)\\)", "", rhs)  # strip offset term
  #rhs <- gsub("log.no.stems", "size", rhs)                    # rename density term
  trimws(rhs)
}

fixed_formulas <- sapply(umbels, get_fixed_formula)

panicles_AICc2$fixed_effects <- fixed_formulas[panicles_AICc2$Modnames]


aic.d <- panicles_AICc2 %>% 
  rename(Model = Modnames) %>% 
  relocate(fixed_effects, .before =1) |> 
  select(c(1, 3, 4, 5))
  #filter(Rank %in% c(1:10, 43)) #also show the intercept only model

aic.d %>% gt() %>% gtsave(here("Tables", "Lomatium", "Lomatium.AIC.table.no.seeds.docx"))

#save the best fit model
summary(poisson.s.trt3)
coefs <- summary(poisson.s.trt3)$coefficients

s.coef <- data.frame(
  Term = rownames(coefs),
  Estimate = coefs[, "Estimate"],
  SE = coefs[, "Std. Error"]
)

write.csv(s.coef, here("Tables", "Lomatium", "lomatium_no.seeds_best_fit_coeff.csv"), row.names = F)
```



```{r number seeds figure}

pred.dat.pan <- expand.grid(size = seq(min(seeds$size, na.rm = TRUE), max(seeds$size, na.rm = TRUE), by = .1), prev_summer.mean.min.temp = c(-1, 1),  trt = c("irrigated", "control", "drought"))
pred.dat.output.pan <- cbind(pred.dat.pan, as.data.frame(predict(poisson.s.trt3, newdata = pred.dat.pan, type="response", re.form=~0, pred.var=TRUE)))
colnames(pred.dat.output.pan)[ncol(pred.dat.output.pan)] <- "no.seeds"  # Renaming the last column

# pred.dat.pan <- expand.grid(size = seq(min(lom$size, na.rm = TRUE), max(lom$size, na.rm = TRUE), by = .1))
# pred.dat.output.pan <- cbind(pred.dat.pan, as.data.frame(predict(poisson.base.size, newdata = pred.dat.pan, type="response", re.form=~0, pred.var=TRUE)))
# colnames(pred.dat.output.pan)[ncol(pred.dat.output.pan)] <- "No.umbels"  # Renaming the last column



(seeds.fig <- seeds %>% 
    filter(no.seeds>0) %>% 
  ggplot(aes(x = size, y = no.seeds))+
  geom_jitter(alpha = 0.25, shape = 1, height = .05, width = 0.05)+
  geom_line(data = pred.dat.output.pan, aes(y = no.seeds, color = factor(prev_summer.mean.min.temp)),linewidth = 1.5) +
  theme(axis.line = element_line(colour = 'black', linewidth = 1.1), legend.position = c(0.05, .85),   legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA))+
  scale_color_manual(values = c("#8cbaec", "#f77550"), labels = c("Cool", "Warm")) +
  facet_wrap(~trt)+
    scale_x_continuous(expand = c(0, 0), limits = c(0, 6))+
  labs(x = "log(Size) in t", y = "Number of seeds in t", color = "Summer min temp, t-1"))

ggsave(here("Figures", "Lomatium", "no.seeds.png"), plot = seeds.fig, width = 8, height =4)

```

```{r}
#  s.f+s.sp
# growth
# flow.fig
# pseeds.fig
# seeds.fig
last_row <- pseeds.fig + plot_spacer() + plot_layout(widths = c(1, 3))

(all <-
  s.sp / growth.fig / flow.fig / seeds.fig / last_row +
   plot_layout(axis_titles = 'collect') +
    plot_annotation(tag_levels = "A", tag_suffix = ")") &
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 10), 
    legend.background = element_rect(fill = NA, colour = NA),
    legend.key = element_rect(fill = NA, colour = NA)
  ))
ggsave(here("Figures", "Lomatium", "all.png"), plot = all, width = 10, height =18)
```

