---
title: "primula.ipm_stoch"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

library(tidyverse)
library(AICcmodavg)
library(lme4)
#library(lmtest)
library(patchwork) #for putting plots into one
library(popbio)

theme_set(theme_classic()) #for ggplot
```


```{r}
primula <- read.csv(here("clean_data", "Primula_Demography_Data_CLEANED_2016thru2026.csv"))
climate <- read.csv(here("clean_data", "CGOP_climatevalues_scaled.csv"))
future.climate <- read.csv(here("clean_data", "CGOP_future_climate_values.csv"))

climate<- climate %>%
  arrange(year) %>%
  mutate(across(-year, ~lag(.x), .names = "prev_{.col}")) %>% 
  select(c(year, winter.mean.min.temp, prev_winter.mean.min.temp, summer.mean.max.temp, prev_summer.mean.max.temp, spring.mean.temp, prev_spring.mean.temp, fall.mean.temp, prev_fall.mean.temp, ends_with("tot.precip"))) 
primula <- left_join(primula, climate)
primula <- primula %>% 
  filter(year!= "2016") %>% 
  group_by(tag) %>% 
  mutate(year = as.factor(year), 
    plot = as.factor(plot),
    psurvival = factor(psurvival, levels = c(0, 1)),
    psurvivalT1 = as.character(psurvivalT1),
    psurvivalT1 = factor(psurvivalT1, levels = c(0, 1)),
    pflower = factor(pflower, levels = c(0, 1)),
    pflowerT1 = factor(pflowerT1, levels = c(0, 1)),
    pclonal = factor(pclonal, levels = c(0, 1)),
    log.ros.area.prev = log(ros.areaTminus1),
    trt = as.factor(trt),
    trt = fct_relevel(trt, "irrigated", "control", "drought")) 
primula.surv <- primula %>% 
  filter(!year %in% c("2025", "2026"),
  !is.na(psurvivalT1))
clonal <- primula %>% 
  filter(log.ros.area>0,
         !is.na(no.neighbors)&!is.na(pclonal),
        !year  == "2026")
leaf <- primula %>% 
  filter(log.ros.area>0,
         no.smleaf>0,
         !is.na(no.neighbors),
         no.smleaf<15)
#these are for the new rosette plants
new.plants <- primula %>%   
  mutate(leaves = if_else(year == 2022, no.smleaf + no.bigleaf, leaves)) %>% 
  filter(year == YrTag) %>% ##need to filter cases where year tagged == year (so newly tagged that year)
  filter(pflower == 0) %>% ## actual new plants definitely can't flower in the first year
  filter(log.ros.area < 4,
         leaves>1|is.na(leaves)) %>% ## can't have more than 3 leaves if youre new
  filter(!is.na(log.ros.area))
climate <- climate %>% 
  mutate(year = as.factor(year)) %>% 
  filter(year != "2015",
         year!= "2016")
```

```{r best fit vital rate models}
gm.st.i <-  lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
#ranef(gm.st.i)
pmflow.ti <-  glmer(pflower ~ log.ros.area.prev*trt + (1|plot) + (1|year), data = subset(primula, year != "2017"), family = "binomial")
nf.wt <-  glmer(flow.sum ~ log.ros.area.prev + prev_winter.mean.min.temp	+(1|plot) + (1|year), data= subset(primula, flow.sum>0), family = "poisson")
sm <- glmer(psurvivalT1 ~ log.ros.area + (1|plot) + (1|year), data = primula, family = "binomial")
probc2 <- glmer(pclonal ~ log.ros.area + (1|plot) + (1|year), data = clonal, family = "binomial")
no_clones2 <- glmer(no.smleaf ~ log.ros.area + (1|plot) + (1|year), data = leaf, family = "poisson")
```

Then the other miscellany we'll need (size independent parameters):
Here, keeping them the saem as chapters 1 and 2 for now
```{r}
prob.seed.germ <- .022 #this is from the seed addition data - average seed has 0.022 chance of germination
prob.seedling.to.1leaf <- .03 #this is estimated from seed miniplots

#if a one leaf survives it will either stay as a one leaf or go to adult. BUT they can die. So. One leafs can either die, stay the same, or grow
#to do: update with 2026 data
prob.1leaf.to.1leaf <- .41*.42 # p that it survives and probability it doesn't become a 2 leaf
prob.1leaf.to.2leaf <- .41*.58 #p that it survives and probability that it becomes an adult

new_sd <- sd(new.plants$log.ros.area)
new_mean <- mean(new.plants$log.ros.area)
hist(new.plants$log.ros.area)

#Define the min and max size, which are the integration bounds of the IPM.
minRealsize <- min(primula$log.ros.area, na.rm=T) 
maxRealsize <- 1.1* max(primula$log.ros.area,na.rm=T)

#now add a new min & max size to keep the plants in for eviction
min.size <-minRealsize-1 #lower
max.size <-maxRealsize+1.5 #upper

```

## Collect model parameters into a df

```{r parameters , echo=FALSE}
#this is for range of climates
rows <- climate %>% 
  select(year, prev_winter.mean.min.temp, spring.mean.temp) %>% 
  expand_grid(
    trt = c("irrigated", "control", "drought"))
#set up an empty parameter df
#add clonal!
params=data.frame(
	growth.int = c(NA),
	growth.slope  = NA,
	growth.sd=NA,
	surv.int=NA,
	surv.slope=NA,
	pflow.int = NA,
	pflow.slope = NA,
	no.flow.int=NA,
	no.flow.slope=NA,
	pclonal.int = NA,
	pclonal.slope = NA,
	no.clone.int = NA,
	no.clone.slope = NA,
	recruit.size.mean=NA,
	recruit.size.sd=NA,
	prob.seed.germ = NA,
	seeds = NA
)
params <- bind_cols(params, rows)

scenarios <- expand.grid(scenario = c("current", "future.precip", "future.temp", "future"))
params <- crossing(params, scenarios)

#add in the future climate variables
climate_vars <- future.climate$variable

for (v in climate_vars) {

  # Skip variables not present in params
  if (v %in% names(params)) {

    delta.precip <- future.climate$future.precip[future.climate$variable == v]
    delta.temp <- future.climate$future.temp[future.climate$variable == v]
    delta <- future.climate$future[future.climate$variable == v]


    params[[v]] <- case_when(
      params$scenario == "current" ~ params[[v]],
      params$scenario == "future.precip" ~ params[[v]] + delta.precip,
      params$scenario == "future.temp" ~ params[[v]] + delta.temp,
      params$scenario == "future" ~ params[[v]] + delta
    )
  }

  # Update corresponding prev_ variable if it exists
  prev_v <- paste0("prev_", v)

  if (prev_v %in% names(params)) {

    delta.precip <- future.climate$future.precip[future.climate$variable == v]
    delta.temp <- future.climate$future.temp[future.climate$variable == v]
    delta <- future.climate$future[future.climate$variable == v]

    params[[prev_v]] <- case_when(
      params$scenario == "current" ~ params[[prev_v]],
      params$scenario == "future.precip" ~ params[[prev_v]] + delta.precip,
      params$scenario == "future.temp" ~ params[[prev_v]] + delta.temp,
      params$scenario == "future" ~ params[[prev_v]] + delta
    )
  }
}


#adding in random effects
#growth
re_year_growth <- ranef(gm.st.i)$year %>%
  rownames_to_column(var = "year") %>%
  rename(growth_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_growth, by = "year") #%>% 
  #filter(!is.na(growth_re))

#pflower
re_year_pflower <- ranef(pmflow.ti)$year %>%
  rownames_to_column(var = "year") %>%
  rename(pflower_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_pflower, by = "year") 

#no flowers
re_year_noflower <- ranef(nf.wt)$year %>%
  rownames_to_column(var = "year") %>%
  rename(noflower_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_noflower, by = "year") 

#survival
re_year_surv <- ranef(sm)$year %>%
  rownames_to_column(var = "year") %>%
  rename(surv_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_surv, by = "year") 

#p clone
re_year_pclones <- ranef(probc2)$year %>%
  rownames_to_column(var = "year") %>%
  rename(pclones_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_pclones, by = "year") 

#no clones
re_year_noclones <- ranef(no_clones2)$year %>%
  rownames_to_column(var = "year") %>%
  rename(noclones_re = `(Intercept)`)

params <- params %>%
  left_join(re_year_noclones, by = "year") 

 ### add in a average year for the SSD for the projections
climate_cols <- c("prev_winter.mean.min.temp", "spring.mean.temp"
)

base_row <- params[1:3, ]

base_row[] <- NA
base_row$trt <- c("irrigated", "control", "drought")
base_row$year <- "base"
base_row$scenario <- "base"
base_row[climate_cols] <- 0

params <- bind_rows(base_row, params)
#for any years without data, make 0 (average RE)
params <- params %>%
  mutate(across(
      c(growth_re, pflower_re, noflower_re,
        surv_re, pclones_re, noclones_re),
      ~ tidyr::replace_na(., 0)))
```


```{r parameters for vital rate models}
#gm.st.i <-  lmer(log.ros.areaT1 ~ log.ros.area*spring.mean.temp + (1|plot) + (1|year), data = primula, REML = F)
# fixef(gm.st.i)
# ranef(gm.st.i)$year
for (i in 1:nrow(params)) {
  params$growth.slope[i] <- fixef(gm.st.i)[2] +fixef(gm.st.i)[4] * params$spring.mean.temp[i]
  params$growth.int[i] <- fixef(gm.st.i)[1] + fixef(gm.st.i)[3] * params$spring.mean.temp[i] + params$growth_re[i]
}

growth_var <- as.data.frame(VarCorr(gm.st.i)) #assumes same variance across all
params$growth.sd <- growth_var[growth_var$grp=="Residual","sdcor"] # growth sd of residuals

### pflower
#pmflow.ti <-  glmer(pflower ~ log.ros.area.prev*trt + (1|plot) + (1|year), data = subset(primula, year != "2017"), family = "binomial")
fixef(pmflow.ti)
#intercept
for (i in 1:nrow(params)) {
params$pflow.int <- case_when(params$trt == "control"~  fixef(pmflow.ti)[1] + fixef(pmflow.ti)[3] +params$pflower_re[i],
                             params$trt == "irrigated"~  fixef(pmflow.ti)[1]+params$pflower_re[i],
                             params$trt == "drought"~  fixef(pmflow.ti)[1] + fixef(pmflow.ti)[4]+params$pflower_re[i])
}
#slope:
params$pflow.slope <- case_when(params$trt == "control"~  fixef(pmflow.ti)[2]+fixef(pmflow.ti)[5],
                             params$trt == "irrigated"~  fixef(pmflow.ti)[2],
                             params$trt == "drought"~  fixef(pmflow.ti)[2] + fixef(pmflow.ti)[6])


### no.flowers
#nf.wt <-  glmer(flow.sum ~ log.ros.area.prev + prev_winter.mean.min.temp	+(1|plot) + (1|year), data= subset(primula, flow.sum>0), family = "poisson")
#slope
for (i in 1:nrow(params)) {
  params$no.flow.slope[i] <- fixef(nf.wt)[2]
  params$no.flow.int[i] <- fixef(nf.wt)[1] + fixef(nf.wt)[3] * params$prev_winter.mean.min.temp[i] + params$noflower_re[i]
}


##survival:
#sm <- glmer(psurvivalT1 ~ log.ros.area + (1|plot) + (1|year), data = primula, family = "binomial")
#slope
params$surv.slope <- fixef(sm)[2]
for (i in 1:nrow(params)) {
  params$surv.int<- fixef(sm)[1] + params$surv_re[i]
}

#flowers in drought plots make 6 seeds, control make 11, irrigated make 13
params$seeds[params$trt == "irrigated"] <- 13
params$seeds[params$trt == "drought"] <- 6
params$seeds[params$trt == "control"] <- 11

#pclonal
#probc2 <- glmer(pclonal ~ log.ros.area + (1|plot) + (1|year), data = clonal, family = "binomial")
#slope
params$pclonal.int <- fixef(probc2)[1]
params$pclonal.slope<- fixef(probc2)[2]

#no_clones2 <- glmer(no.smleaf ~ log.ros.area + (1|plot) + (1|year), data = leaf, family = "poisson")
params$no.clone.int <- fixef(no_clones2)[1]
params$no.clone.slope<- fixef(no_clones2)[2]
#intercept

#params$no.seeds <- no.seeds
params$prob.seed.germ <- prob.seed.germ
params$recruit.size.mean <- new_mean # mean new >1 leaf plant size
params$recruit.size.sd<- new_sd # sd of new >1 leaf plant size

```
# Build the model!

### Step 1. Build vital rate functions (components of the kernel)
_RUN FOR ALL - THESE ARE THE FUNCTIONS FOR ALL THE IPMS_
```{r VR functions}
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
###         Load functions
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#params <- params_expanded #uncheck this for the bootstrapped parameters

#SURVIVAL AT SIZE X
s.x=function(x,params) {
	u=exp(params$surv.int+params$surv.slope*x)
	return(u/(1+u))
}

#how to test this: 
### run function for a plant of size 1 and for the first row of parameters
#s.x(x = 1, params = params[1,])
### run function for a plant of size 1 but for all rows of parameters (so get a list )
#s.x(x = 1, params = params)
#ok this works and seems to work for all rows of params. great.

#GROWTH FROM SIZE X TO Y; 
  ## returns a *probability density distribution* for each x value
g.yx<-function(y,x,params){
    # eviction here...
  xb=pmin(pmax(x,minRealsize),maxRealsize) #Transforms all values below/above limits in min/max size (floor & ceiling)
  growth_to_newsize <-params$growth.int + params$growth.slope*xb
  growth_sd <- params$growth.sd
  return(dnorm(y,mean=growth_to_newsize,sd=growth_sd))
  #dnorm(y,mean=params$growth.int + params$growth.slope*x,sd=params$growth.sd)
}

#Tom Miller's combined s and g kernel
P <- function(y, x, params){
  s.x(x, params)*g.yx(y, x, params)
}

#PROBABILITY OF FLOWERING OF SIZE X individuals
pf.x <-function(x,params){
	u<-exp(params$pflow.int+params$pflow.slope*x)
	return(u/(1+u))
}
#testing this for a plant of size 5
#pf.x(x = 8,params = params_expanded)

f.yx <- function(x,params) { 		
  return(pf.x(x,params)*exp(params$no.flow.int+params$no.flow.slope*x)* params$seeds * params$prob.seed.germ)
}
##so this should be outputting the number of seedlings made? Yes
#f.yx(x = 7,params = params_original)


##do big plants make a million flowers?
#exp(params$no.flow.int+params$no.flow.slope*8) 
## no they make a reasonable amount


cf <- function(x,params) { 		
  return(exp(params$pclonal.int+params$pclonal.slope*x)*exp(params$no.clone.int+params$no.clone.slope*x))
}
#to test:
#cf(x = 5,params = params)
#exp(params$pclonal.int+params$pclonal.slope*2)*exp(params$no.clone.int+params$no.clone.slope*2)


#SIZE DISTRIBUTION OF RECRUITS - so the ones going from the 1 leaf stage into the continuous stage. I'm not sure that this is doing what I want it to - 
recruit.size<-function(y,params){
    ## returns a *probability density distribution*
  dnorm(y,mean=params$recruit.size.mean,sd=params$recruit.size.sd)
}
```

```{r ipm}
#to add in pest for params (uncheck when making that figure)
#make parameters for control and non reproductive plants under mean temperatures (more simple)
#params_list <-  filter(params) %>% split(., seq(nrow(.))) #this splits up params into X rows, which I can feed into the function below
params <- params %>%
  mutate(kernel_id = row_number())

params_list <- params %>%
  split(.$kernel_id)
#if a one leaf survives it will either stay as a one leaf or go to adult. BUT they can die. So. One leafs can either die, stay the same, or grow
prob.1leaf.to.1leaf <- .41*.42 # p that it survives and probability it doesn't become a 2 leaf
prob.1leaf.to.2leaf <- .41*.58 #p that it survives and probability that it becomes an adult
mat.size = 100 #dimensions of continuous matrix
bigmatrix<-function(params_list, mat.size)
  {
  n<-mat.size
  L<-min.size
  U<-max.size
  #these are the upper and lower integration limits
  h<-(U-L)/n                   #Bin size
  b<-L+c(0:n)*h;               #Lower boundaries of bins 
  y<-0.5*(b[1:n]+b[2:(n+1)]);  #Bins' midpoints
  #these are the boundary points (b) and mesh points (y)

  # Fertility matrix
  Fmat<-matrix(0,(n+2),(n+2))
  
  # top row: # seedlings produced by each size class:
  Fmat[1,3:(n+2)]<-f.yx(y,params_list) 
  
  # Growth/survival transition matrix
  Tmat<-matrix(0,(n+2),(n+2))
  
  # probability seedling becomes a 1 leaf plant
  Tmat[2,1]<- prob.seedling.to.1leaf
  
   # probability 1 leaf plant stays as a 1 leaf plant
  Tmat[2,2]<- prob.1leaf.to.1leaf
  
  # clonal growth: addition of 1-leaf plants by adults
  Tmat[2,3:(n+2)] <- cf(y, params_list)
  # clonal growth: addition of 1-leaf plants by adults == 0 (checking what would happen if clonality was zero)
  #Tmat[2,3:(n+2)] <- 0
  
  # Graduation from 1 leaf to cts size = prob 1 leaf becomes a 2 leaf * size dist of new adults
  Tmat[3:(n+2),2]<- prob.1leaf.to.2leaf *recruit.size(y,params_list) * h
  
  # Growth/survival transitions among cts sizes
  Tmat[3:(n+2),3:(n+2)]<- outer(y,y,P,params=params_list) * h 
  
  # Put it all together
  IPMmat<-Fmat+Tmat     #Full Kernel is simply a summation of fertility and transition matrix
  

  out_matrix <- list(
    IPMmat = IPMmat,
    Fmat = Fmat,
    Tmat = Tmat,
    meshpts = y)

  out_lamb <- data.frame(
    Year = params_list$year,
    lambda = lambda(IPMmat),
    scenario = params_list$scenario,
    prev_winter.mean.min.temp = params_list$prev_winter.mean.min.temp,
    spring.mean.temp = params_list$spring.mean.temp,
    trt = params_list$trt,
    kernel_id = params_list$kernel_id)

return(list(
  IPMmat = IPMmat,
  Fmat = Fmat,
  Tmat = Tmat,
  meshpts = y,
  lambda = out_lamb))
}

#what I want returned is lambdas
# lamb_lists <- lapply(X = params_list, FUN = bigmatrix, mat.size = mat.size) #for each row of params_list, run the big matrix function!
# 
# #great~! now make it a df
# primula_lambda <- do.call(rbind, lamb_lists)
results <- lapply(params_list, bigmatrix, mat.size = mat.size)

prim_lambda <- do.call(rbind, lapply(results, function(x) x$lambda)) #run this one to get df of lambdas

kernels <- lapply(results, function(x) x$IPMmat)
kernel_info <- params %>%
  select(year)
##for stochastic:
# kernels <- lapply(params_list, bigmatrix, mat.size = mat.size)
# 
# kernel_info <- params %>%
#   select(year, trt)

```


```{r yearly lambda figure}

# (yearly <- prim_lambda %>%
#    filter(scenario == "current") |> 
#   ggplot(aes(x = Year, y = lambda, group = trt, color = trt)) +
#   geom_line(size = 1.2) +
#   geom_point(size = 1.2) +
#   labs(
#     x = "year",
#     y = expression(lambda)) )

(sp <- prim_lambda %>%
   filter(scenario == "current") |> 
  ggplot(aes(x = spring.mean.temp, y = lambda, color = trt)) +
  geom_point(size = 2) +
     scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3")) +
   geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  labs(x = " Spring mean temperature",
    y = expression(lambda),
    color = ""))
(wt.p <- prim_lambda %>%
   filter(scenario == "current") |> 
    ggplot( aes(x = prev_winter.mean.min.temp, y = lambda, color = trt)) +
  geom_point(size = 2) +
    geom_smooth(
    aes(group = 1),
    method = "lm",
    se = F,
    color = "black")+
  scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3")) +
  labs(
    x = "Previous winter temp",
    y = expression(lambda),
    color = "" ))


 (together <- (wt.p + sp)+  plot_layout(guides = "collect"))

(yearly <- prim_lambda %>%
  ggplot(aes(x = Year, y = lambda, color = trt, group = trt)) +
  geom_line(size = 1.2) +
  geom_point(size = 1.2) +
  facet_wrap(~scenario)+
  scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3")) +
     theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1))+
  labs(
    x = "year",
    y = expression(lambda)) )

ggsave(here("Figures", "Primula", "p.yearly.pop.growth.png"), plot = yearly, width =10, height =5)
ggsave(here("Figures", "Primula", "yearly.pop.growth.by.climate.png"), plot = together, width = 8, height =8)

```

get SSD for stochastic simulations
```{r}
# Base kernel (single kernel)
base_kernels <- kernels[which(prim_lambda$scenario == "base")]

names(base_kernels) <- prim_lambda$trt[prim_lambda$scenario == "base"]#
get_ssd <- function(kernel, N0, years) {
  
  # initial population distribution
  n <- rep(N0 / nrow(kernel), nrow(kernel))
  
  # project population
  for(i in 1:years) {
    
    n <- kernel %*% n
    
    # keep abundance constant, retain size distribution
    n <- n / sum(n) * N0
  }
  
  # stable size distribution
  ssd <- n / sum(n)
  
  return(ssd)
}


# calculate SSD for each treatment
ssd_list <- lapply(base_kernels, get_ssd, N0 = 1000, years = 100)
```


```{r stochastic ipm where climate is 1-2 deg warmer/precip changes}
scenario_idx <- prim_lambda$scenario != "base"

scenario_kernels <- lapply(split(seq_along(kernels)[scenario_idx], 
                                 prim_lambda$trt[scenario_idx]), function(idx) {
  split(kernels[idx], prim_lambda$scenario[idx])
})
names(scenario_kernels)
names(scenario_kernels$irrigated)


stochastic_ipm <- function(scenario_kernels, ssd_list, N0, years, reps) {
  
  lambda_summary <- list()
  
  counter <- 1
  
  for(trt in names(scenario_kernels)) {
    
    trt_kernels <- scenario_kernels[[trt]]
    ssd <- ssd_list[[trt]]
    
    for(sc in names(trt_kernels)) {
      
      kernel_list <- trt_kernels[[sc]]
      
      rep_lambda <- numeric(reps)
      
      for(r in 1:reps) {
        
        # start from treatment-specific SSD
        n <- ssd * N0
        
        annual_lambda <- numeric(years)
        
        for(t in 1:years) {
          
          N_before <- sum(n)
          
          # sample yearly climate kernel
          K <- kernel_list[[sample(seq_along(kernel_list), 1)]]
          
          # project population
          n <- K %*% n
          
          N_after <- sum(n)
          
          annual_lambda[t] <- N_after / N_before
        }
        
        rep_lambda[r] <- exp(mean(log(annual_lambda)))
      }
      
      lambda_s <- exp(mean(log(rep_lambda)))
      
      lambda_CI <- quantile(rep_lambda, c(0.025, 0.975))
      
      lambda_summary[[counter]] <- data.frame(
        trt = trt,
        scenario = sc,
        stochastic_lambda = lambda_s,
        lower_CI = lambda_CI[1],
        upper_CI = lambda_CI[2]
      )
      
      counter <- counter + 1
    }
  }
  
  return(do.call(rbind, lambda_summary))
}

stoch_lambda <- stochastic_ipm(
  scenario_kernels = scenario_kernels,
  ssd_list = ssd_list,
  N0 = 1000,
  years = 100,
  reps = 10000
)
write.csv(stoch_lambda, here("clean_data", "stoch_ipm", "primula.stoch.lambda.csv"), row.names = FALSE)

```

```{r}
(
p.s <- stoch_lambda |> 
  filter(scenario != "future") |> 
  ggplot(
       aes(x = scenario, y = stochastic_lambda, color = trt)) +
  geom_point(size = 4,
             position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = lower_CI, ymax = upper_CI),
                width = 0.15,
                linewidth = 1,
                position = position_dodge(width = 0.4)) +
  geom_hline(yintercept = 1, 
             linetype = "dashed", 
             color = "grey") +
  scale_x_discrete(
    labels = c(
      "current" = "Current",
      "future.precip" = "Precip change",
      "future.temp" = "Temp change",
      "future" = "Future"
    )
  ) +
    scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3")) +
  labs(
    x = "", color = "",
    y = "Stochastic lambda (λs)",
    title = "Lomatium"
  ))

ggsave(here("Figures", "Primula", "STOCH_LAM_SCENARIOS.png"), plot = p.s, width = 8, height =6)

```







































```{r drought sim}
drought_idx <- which(kernel_info$trt == "drought")
drought_kernels <- kernels[drought_idx]

K <- drought_kernels[[sample.int(length(drought_kernels), 1)]]
stochastic_lambda <- function(kernels, T = 1000, burn = 500) {

  n <- nrow(kernels[[1]])

  # initial population
  N <- rep(1, n)
  N <- N / sum(N)

  log_growth <- numeric(T)

  for (t in seq_len(T)) {

    # sample one year's kernel
    K <- kernels[[sample.int(length(kernels), 1)]]

    N_next <- K %*% N

    log_growth[t] <- log(sum(N_next))

    N <- N_next / sum(N_next)
  }

  exp(mean(log_growth[(burn + 1):T]))
}

stoch_lambdas <- replicate(
  1000,
  stochastic_lambda(kernels)
)

mean(stoch_lambdas)
quantile(stoch_lambdas, c(0.025, 0.975))
```

```{r control sim}
control_idx <- which(kernel_info$trt == "control")
control_kernels <- kernels[control_idx]

K <- control_kernels[[sample.int(length(control_kernels), 1)]]
stochastic_lambda <- function(kernels, T = 1000, burn = 500) {

  n <- nrow(kernels[[1]])

  # initial population
  N <- rep(1, n)
  N <- N / sum(N)

  log_growth <- numeric(T)

  for (t in seq_len(T)) {

    # sample one year's kernel
    K <- kernels[[sample.int(length(kernels), 1)]]

    N_next <- K %*% N

    log_growth[t] <- log(sum(N_next))

    N <- N_next / sum(N_next)
  }

  exp(mean(log_growth[(burn + 1):T]))
}

stoch_lambdas <- replicate(
  1000,
  stochastic_lambda(kernels)
)

mean(stoch_lambdas)
quantile(stoch_lambdas, c(0.025, 0.975))
```


```{r}
#y_limits <- c(1.05, 1.2)
(yearly <- primula_lambda %>%
  #filter(prev_winter.mean.min.temp ==0) %>% 
  ggplot(aes(x = year, y = lambda, color = trt, group = trt)) +
  geom_line(size = 1.2) +
  #scale_y_continuous(limits = y_limits) +
  scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3"))+
  labs(
    x = "year",
    y = expression(lambda),
    color = ""
  ) )
(spring <- ggplot(primula_lambda, aes(x = spring.mean.temp, y = lambda, color = factor(year))) +
  geom_point(size = 2) +
  theme_minimal() +
  scale_x_continuous(limits = c(-2, 1)) +
  labs(
    x = "Spring mean temperature",
    y = expression(lambda),
    color = "Year" ))
(winter <- ggplot(primula_lambda, aes(x = prev_winter.mean.min.temp, y = lambda, color = factor(year))) +
  geom_point(size = 2) +
  theme_minimal() +
    scale_x_continuous(limits = c(-2, 1)) +
  labs(x = "Winter mean temperature",
    y = expression(lambda),
    color = "Year"))
# (sp.temp <- dac_lambda %>%
#   filter(summer.tot.precip == 0, summer.mean.max.temp == 0) %>% 
#   ggplot(aes(x = spring.temp, y = lambda, color = trt)) +
#   geom_line(size = 1.2) +
#   scale_y_continuous(limits = y_limits) +
#   scale_color_manual(values = c("#9fb764", "#e54e21", "#3088a3"))+
#   labs(
#     x = "Spring Temperature",
#     y = expression(lambda),
#     color = ""
#   ) )
 (together <- spring/winter+ plot_layout(guides = "collect", axis_titles = "collect"))

ggsave(here("Figures", "Primula", "primula.yearly.pop.growth.png"), plot = yearly, width = 7.5, height =5)
ggsave(here("Figures", "Primula", "primula.yearly.pop.growth.by.climate.png"), plot = together, width = 7.5, height =7.5)

```

